query GetFormShareData($shareId: ID!) {
  share(id: $shareId) {
    enabled
    id
    target {
      id
      type
    }
  }

  tableByShare(shareId: $shareId) {
    id
    forms {
      description
      fields
      id
      name
      option {
        backgroundColor
      }
      fields
    }
    views {
      id
      name
      fields
    }
    schema {
      constraint
      defaultValue
      display
      id
      name
      option
      type
    }
  }
}
