query GetTableForeignTables($tableId: ID!) {
  tableForeignTables(tableId: $tableId) {
    id
    name
    base {
      id
      name
    }
    schema {
      id
      name
      type
      defaultValue
      display
      constraint
      option
      metadata
    }
    views {
      id
      name
      type
      filter
      color
      sort
      aggregate
      fields
    }
  }
}
