CREATE TABLE "undb_api_token" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"user_id" text NOT NULL,
	"space_id" text NOT NULL,
	"token" text NOT NULL,
	CONSTRAINT "undb_api_token_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE "undb_attachment_mapping" (
	"attachment_id" text NOT NULL,
	"table_id" text NOT NULL,
	"record_id" text NOT NULL,
	"field_id" text NOT NULL,
	CONSTRAINT "undb_attachment_mapping_attachment_id_table_id_record_id_field_id_pk" PRIMARY KEY("attachment_id","table_id","record_id","field_id")
);
--> statement-breakpoint
CREATE TABLE "undb_attachment" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"size" integer NOT NULL,
	"mime_type" text NOT NULL,
	"url" text NOT NULL,
	"token" text,
	"created_at" bigint NOT NULL,
	"created_by" text NOT NULL,
	"space_id" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "undb_audit" (
	"id" text PRIMARY KEY NOT NULL,
	"timestamp" bigint NOT NULL,
	"detail" jsonb,
	"meta" jsonb,
	"op" text NOT NULL,
	"table_id" text NOT NULL,
	"record_id" text NOT NULL,
	"operator_id" text NOT NULL,
	"space_id" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "undb_base" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"space_id" text NOT NULL,
	"created_at" text DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
	"created_by" text NOT NULL,
	"updated_at" text NOT NULL,
	"updated_by" text NOT NULL,
	CONSTRAINT "base_name_unique_idx" UNIQUE("name","space_id")
);
--> statement-breakpoint
CREATE TABLE "undb_dashboard_table_id_mapping" (
	"dashboard_id" text NOT NULL,
	"table_id" text NOT NULL,
	CONSTRAINT "undb_dashboard_table_id_mapping_dashboard_id_table_id_pk" PRIMARY KEY("dashboard_id","table_id")
);
--> statement-breakpoint
CREATE TABLE "undb_dashboard" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"base_id" text NOT NULL,
	"space_id" text NOT NULL,
	"widgets" jsonb,
	"layout" jsonb,
	"created_at" text DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
	"created_by" text NOT NULL,
	"updated_at" text NOT NULL,
	"updated_by" text NOT NULL,
	CONSTRAINT "dashboard_name_unique_idx" UNIQUE("name","base_id")
);
--> statement-breakpoint
CREATE TABLE "undb_email_verification_code" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "undb_email_verification_code_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"code" text NOT NULL,
	"user_id" text,
	"email" text NOT NULL,
	"expires_at" bigint NOT NULL,
	CONSTRAINT "undb_email_verification_code_user_id_unique" UNIQUE("user_id")
);
--> statement-breakpoint
CREATE TABLE "undb_invitation" (
	"id" text PRIMARY KEY NOT NULL,
	"email" text NOT NULL,
	"role" text NOT NULL,
	"status" text NOT NULL,
	"space_id" text NOT NULL,
	"invited_at" bigint NOT NULL,
	"inviter_id" text NOT NULL,
	CONSTRAINT "invitation_unique_idx" UNIQUE("email","space_id")
);
--> statement-breakpoint
CREATE TABLE "undb_oauth_account" (
	"provider_id" text NOT NULL,
	"provider_user_id" text NOT NULL,
	"user_id" text NOT NULL,
	CONSTRAINT "undb_oauth_account_provider_id_provider_user_id_pk" PRIMARY KEY("provider_id","provider_user_id")
);
--> statement-breakpoint
CREATE TABLE "undb_outbox" (
	"id" text PRIMARY KEY NOT NULL,
	"payload" jsonb NOT NULL,
	"meta" jsonb,
	"timestamp" bigint NOT NULL,
	"user_id" text,
	"name" text NOT NULL,
	"space_id" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "undb_password_reset_token" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "undb_password_reset_token_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"token" text NOT NULL,
	"user_id" text NOT NULL,
	"expires_at" bigint NOT NULL,
	CONSTRAINT "undb_password_reset_token_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE "undb_reference_id_mapping" (
	"field_id" text NOT NULL,
	"table_id" text NOT NULL,
	"symmetric_field_id" text,
	"foreign_table_id" text NOT NULL,
	CONSTRAINT "reference_id_mapping_unique_idx" UNIQUE("field_id","table_id","symmetric_field_id","foreign_table_id")
);
--> statement-breakpoint
CREATE TABLE "undb_rollup_id_mapping" (
	"field_id" text NOT NULL,
	"table_id" text NOT NULL,
	"rollup_id" text NOT NULL,
	"rollup_table_id" text NOT NULL,
	CONSTRAINT "undb_rollup_id_mapping_field_id_rollup_id_pk" PRIMARY KEY("field_id","rollup_id")
);
--> statement-breakpoint
CREATE TABLE "undb_session" (
	"id" text PRIMARY KEY NOT NULL,
	"user_id" text NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"space_id" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "undb_share" (
	"id" text PRIMARY KEY NOT NULL,
	"target_type" text NOT NULL,
	"target_id" text NOT NULL,
	"enabled" boolean NOT NULL,
	"space_id" text NOT NULL,
	CONSTRAINT "share_unique_idx" UNIQUE("target_type","target_id")
);
--> statement-breakpoint
CREATE TABLE "undb_space" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text,
	"is_personal" boolean NOT NULL,
	"avatar" text,
	"created_at" text DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
	"created_by" text NOT NULL,
	"updated_at" text NOT NULL,
	"updated_by" text NOT NULL,
	"deleted_at" bigint,
	"deleted_by" text
);
--> statement-breakpoint
CREATE TABLE "undb_space_member" (
	"id" text PRIMARY KEY NOT NULL,
	"user_id" text NOT NULL,
	"role" text NOT NULL,
	"space_id" text NOT NULL,
	CONSTRAINT "space_member_unique_idx" UNIQUE("user_id","space_id")
);
--> statement-breakpoint
CREATE TABLE "undb_table_id_mapping" (
	"table_id" text NOT NULL,
	"subject_id" text NOT NULL,
	CONSTRAINT "undb_table_id_mapping_table_id_subject_id_pk" PRIMARY KEY("table_id","subject_id")
);
--> statement-breakpoint
CREATE TABLE "undb_table" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"base_id" text NOT NULL,
	"space_id" text NOT NULL,
	"schema" jsonb NOT NULL,
	"views" jsonb NOT NULL,
	"forms" jsonb,
	"rls" jsonb,
	"widgets" jsonb,
	"created_at" text DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
	"created_by" text NOT NULL,
	"updated_at" text NOT NULL,
	"updated_by" text NOT NULL,
	CONSTRAINT "table_name_unique_idx" UNIQUE("name","base_id")
);
--> statement-breakpoint
CREATE TABLE "undb_user" (
	"id" text PRIMARY KEY NOT NULL,
	"username" text NOT NULL,
	"email" text NOT NULL,
	"email_verified" boolean DEFAULT false NOT NULL,
	"password" text NOT NULL,
	"avatar" text,
	"otp_secret" text,
	CONSTRAINT "undb_user_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "undb_webhook" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"url" text NOT NULL,
	"method" text NOT NULL,
	"enabled" boolean NOT NULL,
	"table_id" text NOT NULL,
	"headers" jsonb NOT NULL,
	"condition" jsonb,
	"event" text NOT NULL,
	"space_id" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "undb_api_token" ADD CONSTRAINT "undb_api_token_user_id_undb_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."undb_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "undb_api_token" ADD CONSTRAINT "undb_api_token_space_id_undb_space_id_fk" FOREIGN KEY ("space_id") REFERENCES "public"."undb_space"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "undb_attachment_mapping" ADD CONSTRAINT "undb_attachment_mapping_attachment_id_undb_attachment_id_fk" FOREIGN KEY ("attachment_id") REFERENCES "public"."undb_attachment"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "undb_attachment_mapping" ADD CONSTRAINT "undb_attachment_mapping_table_id_undb_table_id_fk" FOREIGN KEY ("table_id") REFERENCES "public"."undb_table"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "undb_attachment" ADD CONSTRAINT "undb_attachment_created_by_undb_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."undb_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "undb_attachment" ADD CONSTRAINT "undb_attachment_space_id_undb_space_id_fk" FOREIGN KEY ("space_id") REFERENCES "public"."undb_space"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "undb_audit" ADD CONSTRAINT "undb_audit_space_id_undb_space_id_fk" FOREIGN KEY ("space_id") REFERENCES "public"."undb_space"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "undb_base" ADD CONSTRAINT "undb_base_space_id_undb_space_id_fk" FOREIGN KEY ("space_id") REFERENCES "public"."undb_space"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "undb_base" ADD CONSTRAINT "undb_base_created_by_undb_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."undb_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "undb_base" ADD CONSTRAINT "undb_base_updated_by_undb_user_id_fk" FOREIGN KEY ("updated_by") REFERENCES "public"."undb_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "undb_dashboard_table_id_mapping" ADD CONSTRAINT "undb_dashboard_table_id_mapping_dashboard_id_undb_dashboard_id_fk" FOREIGN KEY ("dashboard_id") REFERENCES "public"."undb_dashboard"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "undb_dashboard_table_id_mapping" ADD CONSTRAINT "undb_dashboard_table_id_mapping_table_id_undb_table_id_fk" FOREIGN KEY ("table_id") REFERENCES "public"."undb_table"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "undb_dashboard" ADD CONSTRAINT "undb_dashboard_base_id_undb_base_id_fk" FOREIGN KEY ("base_id") REFERENCES "public"."undb_base"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "undb_dashboard" ADD CONSTRAINT "undb_dashboard_space_id_undb_space_id_fk" FOREIGN KEY ("space_id") REFERENCES "public"."undb_space"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "undb_dashboard" ADD CONSTRAINT "undb_dashboard_created_by_undb_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."undb_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "undb_dashboard" ADD CONSTRAINT "undb_dashboard_updated_by_undb_user_id_fk" FOREIGN KEY ("updated_by") REFERENCES "public"."undb_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "undb_email_verification_code" ADD CONSTRAINT "undb_email_verification_code_user_id_undb_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."undb_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "undb_invitation" ADD CONSTRAINT "undb_invitation_space_id_undb_space_id_fk" FOREIGN KEY ("space_id") REFERENCES "public"."undb_space"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "undb_invitation" ADD CONSTRAINT "undb_invitation_inviter_id_undb_user_id_fk" FOREIGN KEY ("inviter_id") REFERENCES "public"."undb_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "undb_oauth_account" ADD CONSTRAINT "undb_oauth_account_user_id_undb_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."undb_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "undb_outbox" ADD CONSTRAINT "undb_outbox_space_id_undb_space_id_fk" FOREIGN KEY ("space_id") REFERENCES "public"."undb_space"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "undb_password_reset_token" ADD CONSTRAINT "undb_password_reset_token_user_id_undb_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."undb_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "undb_session" ADD CONSTRAINT "undb_session_user_id_undb_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."undb_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "undb_session" ADD CONSTRAINT "undb_session_space_id_undb_space_id_fk" FOREIGN KEY ("space_id") REFERENCES "public"."undb_space"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "undb_share" ADD CONSTRAINT "undb_share_space_id_undb_space_id_fk" FOREIGN KEY ("space_id") REFERENCES "public"."undb_space"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "undb_space" ADD CONSTRAINT "undb_space_created_by_undb_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."undb_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "undb_space" ADD CONSTRAINT "undb_space_updated_by_undb_user_id_fk" FOREIGN KEY ("updated_by") REFERENCES "public"."undb_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "undb_space" ADD CONSTRAINT "undb_space_deleted_by_undb_user_id_fk" FOREIGN KEY ("deleted_by") REFERENCES "public"."undb_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "undb_space_member" ADD CONSTRAINT "undb_space_member_user_id_undb_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."undb_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "undb_space_member" ADD CONSTRAINT "undb_space_member_space_id_undb_space_id_fk" FOREIGN KEY ("space_id") REFERENCES "public"."undb_space"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "undb_table_id_mapping" ADD CONSTRAINT "undb_table_id_mapping_table_id_undb_table_id_fk" FOREIGN KEY ("table_id") REFERENCES "public"."undb_table"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "undb_table" ADD CONSTRAINT "undb_table_base_id_undb_base_id_fk" FOREIGN KEY ("base_id") REFERENCES "public"."undb_base"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "undb_table" ADD CONSTRAINT "undb_table_space_id_undb_space_id_fk" FOREIGN KEY ("space_id") REFERENCES "public"."undb_space"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "undb_table" ADD CONSTRAINT "undb_table_created_by_undb_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."undb_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "undb_table" ADD CONSTRAINT "undb_table_updated_by_undb_user_id_fk" FOREIGN KEY ("updated_by") REFERENCES "public"."undb_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "undb_webhook" ADD CONSTRAINT "undb_webhook_table_id_undb_table_id_fk" FOREIGN KEY ("table_id") REFERENCES "public"."undb_table"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "undb_webhook" ADD CONSTRAINT "undb_webhook_space_id_undb_space_id_fk" FOREIGN KEY ("space_id") REFERENCES "public"."undb_space"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "api_token_space_id_idx" ON "undb_api_token" USING btree ("space_id");--> statement-breakpoint
CREATE INDEX "api_token_user_id_idx" ON "undb_api_token" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "attachment_size_idx" ON "undb_attachment" USING btree ("size");--> statement-breakpoint
CREATE INDEX "attachment_space_id_idx" ON "undb_attachment" USING btree ("space_id");--> statement-breakpoint
CREATE INDEX "audit_table_id_idx" ON "undb_audit" USING btree ("table_id");--> statement-breakpoint
CREATE INDEX "audit_space_id_idx" ON "undb_audit" USING btree ("space_id");--> statement-breakpoint
CREATE INDEX "audit_record_id_idx" ON "undb_audit" USING btree ("record_id");--> statement-breakpoint
CREATE INDEX "base_space_id_idx" ON "undb_base" USING btree ("space_id");--> statement-breakpoint
CREATE INDEX "dashboard_base_id_idx" ON "undb_dashboard" USING btree ("base_id");--> statement-breakpoint
CREATE INDEX "dashboard_space_id_idx" ON "undb_dashboard" USING btree ("space_id");--> statement-breakpoint
CREATE INDEX "invitation_space_id_idx" ON "undb_invitation" USING btree ("space_id");--> statement-breakpoint
CREATE INDEX "outbox_space_id_idx" ON "undb_outbox" USING btree ("space_id");--> statement-breakpoint
CREATE INDEX "password_reset_token_user_id_idx" ON "undb_password_reset_token" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "share_space_id_idx" ON "undb_share" USING btree ("space_id");--> statement-breakpoint
CREATE INDEX "space_name_idx" ON "undb_space" USING btree ("name");--> statement-breakpoint
CREATE INDEX "table_base_id_idx" ON "undb_table" USING btree ("base_id");--> statement-breakpoint
CREATE INDEX "table_space_id_idx" ON "undb_table" USING btree ("space_id");--> statement-breakpoint
CREATE INDEX "user_username_idx" ON "undb_user" USING btree ("username");--> statement-breakpoint
CREATE INDEX "user_email_idx" ON "undb_user" USING btree ("email");--> statement-breakpoint
CREATE INDEX "webhook_table_id_idx" ON "undb_webhook" USING btree ("table_id");--> statement-breakpoint
CREATE INDEX "webhook_space_id_idx" ON "undb_webhook" USING btree ("space_id");--> statement-breakpoint
CREATE INDEX "webhook_url_idx" ON "undb_webhook" USING btree ("url");