export * from "./table-base-id.specification"
export * from "./table-forms.specification"
export * from "./table-id.specification"
export * from "./table-name.specification"
export * from "./table-rls.specification"
export * from "./table-schema.specification"
export * from "./table-space-id.specification"
export * from "./table-view.specification"
export * from "./table-views.specification"
export * from "./table-visitor.interface"
export { TableComositeSpecification } from "./table.composite-specification"
export * from "./table.specification"
