export * from "./table-id.specification"
export * from "./table-name.specification"
export * from "./table-schema.specification"
export * from "./table-views.specification"
export * from "./table-visitor.interface"
export { TableComositeSpecification } from "./table.composite-specification"
