import type { IFieldType } from '@undb/core'
import {
  RecordId,
  attachmentFieldQueryValue,
  autoIncrementQueryValue,
  averageFieldQueryValue,
  boolFieldQueryValue,
  collaboratorFieldQueryValue,
  colorFieldQueryValue,
  countFieldQueryValue,
  createdAtFieldQueryValue,
  createdByFieldQueryValue,
  currencyFieldQueryValue,
  dateFieldQueryValue,
  dateRangeFieldQueryValue,
  emailFieldQueryValue,
  idFieldQueryValue,
  lookupFieldQueryValue,
  multiSelectFieldQueryValue,
  numberFieldQueryValue,
  parentFieldQueryValue,
  ratingFieldQueryValue,
  referenceFieldQueryValue,
  selectFieldQueryValue,
  stringFieldQueryValue,
  sumFieldQueryValue,
  treeFieldQueryValue,
  updatedAtFieldQueryValue,
  updatedByFieldQueryValue,
} from '@undb/core'
import type { ZodType } from 'zod'

export const createOpenAPIRecordValueSchema = (): Record<IFieldType, ZodType> => ({
  string: stringFieldQueryValue,
  number: numberFieldQueryValue,
  id: idFieldQueryValue.openapi({ example: RecordId.createId() }),
  'created-at': createdAtFieldQueryValue.openapi({ example: new Date().toISOString() }),
  'updated-at': updatedAtFieldQueryValue.openapi({ example: new Date().toISOString() }),
  'auto-increment': autoIncrementQueryValue,
  color: colorFieldQueryValue,
  email: emailFieldQueryValue,
  date: dateFieldQueryValue,
  select: selectFieldQueryValue,
  'multi-select': multiSelectFieldQueryValue,
  bool: boolFieldQueryValue,
  'date-range': dateRangeFieldQueryValue,
  reference: referenceFieldQueryValue,
  tree: treeFieldQueryValue,
  parent: parentFieldQueryValue,
  rating: ratingFieldQueryValue,
  currency: currencyFieldQueryValue,
  count: countFieldQueryValue,
  lookup: lookupFieldQueryValue,
  sum: sumFieldQueryValue,
  average: averageFieldQueryValue,
  attachment: attachmentFieldQueryValue,
  collaborator: collaboratorFieldQueryValue,
  'created-by': createdByFieldQueryValue,
  'updated-by': updatedByFieldQueryValue,
})
