query GetTableQuery($tableId: ID!, $viewId: ID) {
  table(id: $tableId) {
    id
    name
    schema {
      id
      name
      type
      constraint
    }

    views {
      id
      name
      type
      filter
      color
      sort
      aggregate
    }

    forms {
      id
      name
      fields
    }

    viewData(viewId: $viewId) {
      aggregate
    }

    recordsCount
  }
}
