query GetTableQuery($tableId: ID!) {
  table(id: $tableId) {
    id
    name
    schema {
      id
      name
      type
      constraint
    }
    views {
      id
      name
      type
      filter
      color
      sort
      aggregate
    }
    recordsCount
  }
}
