query GetTableQuery($tableId: ID!, $viewId: ID) {
  table(id: $tableId) {
    id
    name
    schema {
      id
      name
      type
      defaultValue
      display
      constraint
    }

    views {
      id
      name
      type
      filter
      color
      sort
      aggregate
    }

    forms {
      id
      name
      description
      fields
    }

    viewData(viewId: $viewId) {
      aggregate
    }

    rls {
      id
      name
      allow
      enabled
      subject
      action
      condition
      updateCondition
    }

    recordsCount
  }
}
