export * from './bool.specification'
export * from './date-range.specification'
export * from './date.specification'
export type { IRecordSpec, IRecordVisitor } from './interface'
export * from './null.specification'
export * from './number.specification'
export * from './record-created-at.specification'
export * from './record-id.specifaction'
export * from './record-table-id.specification'
export * from './record-values.specification'
export * from './select.specification'
export * from './string.specification'
