export type { IRecordSpec, IRecordVisitor } from './interface'
export * from './number.specification'
export * from './record-id.specifaction'
export * from './record-table-id.specification'
export * from './string.specification'
