query GetCreateFromShareData($shareId: ID!) {
  space {
    id
    name
  }

  template(shareId: $shareId) {
    name
  }

  spaces {
    id
    name
    isPersonal
    member {
      role
    }
  }
}
