export * from '../view/specifications/filters.specificaiton'
export type { ITableSpec, ITableSpecVisitor } from './interface'
export * from './table-field.specification'
export * from './table-id.specifaction'
export * from './table-name.specification'
export * from './table-schema.specification'
