export * from './filters.specificaiton'
export type { ITableSpec, ITableSpecVisitor } from './interface'
export * from './table-field.specification'
export * from './table-id.specifaction'
export * from './table-name.specification'
