query GetLoginSettings {
  settings {
    registration {
      enabled
    }
    auth {
      otp {
        enabled
      }
    }
    oauth {
      google {
        enabled
      }
      github {
        enabled
      }
    }
  }
}
