query GetDashboardQuery($dashboardId: ID!) {
  dashboard(id: $dashboardId) {
    id
    name
    description
    baseId
    spaceId
    layout
    widgets {
      table {
        id
      }
      widget {
        id
        name
        item
      }
    }

    share {
      enabled
      id
    }
  }
}
