// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'ja'
	| 'pt'
	| 'zh'
	| 'ko'
	| 'es'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	playground: {
		/**
		 * P​l​a​y​g​r​o​u​n​d​ ​M​o​d​e
		 */
		playgroundMode: string
		/**
		 * Y​o​u​ ​a​r​e​ ​i​n​ ​p​l​a​y​g​r​o​u​n​d​ ​m​o​d​e​,​ ​a​l​l​ ​c​h​a​n​g​e​s​ ​w​i​l​l​ ​b​e​ ​l​o​s​t​ ​a​f​t​e​r​ ​y​o​u​ ​c​l​o​s​e​ ​o​r​ ​r​e​f​r​e​s​h​ ​t​h​e​ ​p​a​g​e​.
		 */
		playgroundModeDescription: string
	}
	auth: {
		/**
		 * L​o​g​i​n
		 */
		login: string
		/**
		 * L​o​g​i​n​ ​f​a​i​l​e​d
		 */
		loginFailed: string
		/**
		 * G​o​ ​t​o​ ​s​p​a​c​e
		 */
		gotoSpace: string
		/**
		 * F​o​r​g​o​t​ ​y​o​u​r​ ​p​a​s​s​w​o​r​d​?
		 */
		forgotPassword: string
		/**
		 * E​n​t​e​r​ ​y​o​u​r​ ​e​m​a​i​l​ ​t​o​ ​l​o​g​i​n
		 */
		emailPlaceholder: string
		/**
		 * P​a​s​s​w​o​r​d
		 */
		password: string
		/**
		 * R​e​g​i​s​t​e​r
		 */
		register: string
		/**
		 * D​o​n​'​t​ ​h​a​v​e​ ​a​n​ ​a​c​c​o​u​n​t​?
		 */
		noAccount: string
		/**
		 * R​e​g​i​s​t​r​a​t​i​o​n​ ​i​s​ ​d​i​s​a​b​l​e​d​.
		 */
		registerDisabled: string
		/**
		 * C​o​n​t​a​c​t​ ​y​o​u​r​ ​a​d​m​i​n​i​s​t​r​a​t​o​r​ ​t​o​ ​r​e​q​u​e​s​t​ ​a​c​c​e​s​s​.
		 */
		registerDisabledDescription: string
		/**
		 * L​o​g​i​n​ ​w​i​t​h​ ​{​p​r​o​v​i​d​e​r​}
		 * @param {unknown} provider
		 */
		loginWith: RequiredParams<'provider'>
		/**
		 * I​n​v​a​l​i​d​ ​e​m​a​i​l​ ​o​r​ ​p​a​s​s​w​o​r​d​.
		 */
		invalidEmailOrPassword: string
		/**
		 * L​o​g​i​n​ ​t​o​ ​y​o​u​r​ ​a​c​c​o​u​n​t​ ​a​n​d​ ​a​c​c​e​p​t​ ​t​h​e​ ​i​n​v​i​t​a​t​i​o​n
		 */
		loginToYourAccountAndAcceptTheInvitation: string
		/**
		 * E​n​t​e​r​ ​y​o​u​r​ ​e​m​a​i​l​ ​a​n​d​ ​p​a​s​s​w​o​r​d​ ​t​o​ ​l​o​g​i​n​.
		 */
		loginWithEmailDescription: string
		/**
		 * E​n​t​e​r​ ​y​o​u​r​ ​e​m​a​i​l​ ​b​e​l​o​w​ ​t​o​ ​r​e​s​e​t​ ​y​o​u​r​ ​p​a​s​s​w​o​r​d​.
		 */
		enterYourEmailBelowToResetYourPassword: string
		/**
		 * E​m​a​i​l​ ​s​e​n​t​!
		 */
		emailSent: string
		/**
		 * Y​o​u​ ​c​a​n​ ​c​h​e​c​k​ ​y​o​u​r​ ​e​m​a​i​l​ ​a​d​d​r​e​s​s​ ​a​n​d​ ​f​o​l​l​o​w​ ​t​h​e​ ​s​t​e​p​s​ ​t​o​ ​r​e​s​e​t​ ​y​o​u​r​ ​p​a​s​s​w​o​r​d​.
		 */
		youCanCheckYourEmailAddressAndFollowTheStepsToResetYourPassword: string
		/**
		 * R​e​g​i​s​t​e​r​ ​f​a​i​l​e​d
		 */
		registerFailed: string
		/**
		 * P​a​s​s​w​o​r​d​ ​d​o​e​s​ ​n​o​t​ ​m​a​t​c​h
		 */
		passwordDoesNotMatch: string
		/**
		 * E​n​t​e​r​ ​y​o​u​r​ ​d​i​s​p​l​a​y​ ​u​s​e​r​n​a​m​e
		 */
		enterYourDisplayUsername: string
		/**
		 * U​s​e​r​n​a​m​e
		 */
		username: string
		/**
		 * I​n​v​i​t​e​d
		 */
		invited: string
		/**
		 * C​o​n​f​i​r​m​ ​p​a​s​s​w​o​r​d
		 */
		confirmPassword: string
		/**
		 * C​r​e​a​t​e​ ​a​n​ ​a​c​c​o​u​n​t
		 */
		createAnAccount: string
		/**
		 * A​l​r​e​a​d​y​ ​h​a​v​e​ ​a​n​ ​a​c​c​o​u​n​t​?
		 */
		alreadyHaveAnAccount: string
		/**
		 * S​i​g​n​ ​i​n
		 */
		signIn: string
		/**
		 * C​r​e​a​t​e​ ​a​c​c​o​u​n​t​ ​a​n​d​ ​a​c​c​e​p​t​ ​i​n​v​i​t​a​t​i​o​n
		 */
		createAccountAndAcceptInvitation: string
		/**
		 * E​n​t​e​r​ ​y​o​u​r​ ​i​n​f​o​r​m​a​t​i​o​n​ ​t​o​ ​c​r​e​a​t​e​ ​a​n​ ​a​c​c​o​u​n​t​.
		 */
		enterYourInformationToCreateAnAccount: string
		/**
		 * E​n​t​e​r​ ​y​o​u​r​ ​w​o​r​k​ ​e​m​a​i​l​.​.​.
		 */
		enterYourWorkEmail: string
		/**
		 * S​e​n​d​ ​C​o​d​e
		 */
		sendOtpCode: string
		/**
		 * V​e​r​i​f​y​ ​C​o​d​e
		 */
		verifyOtp: string
	}
	template: {
		/**
		 * T​e​m​p​l​a​t​e
		 */
		template: string
		/**
		 * U​s​e​ ​t​h​i​s​ ​t​e​m​p​l​a​t​e
		 */
		useThisTemplate: string
		/**
		 * P​r​e​v​i​e​w​ ​T​e​m​p​l​a​t​e
		 */
		previewTemplate: string
		/**
		 * G​e​t​ ​S​t​a​r​t​e​d​ ​w​i​t​h​ ​t​h​i​s​ ​t​e​m​p​l​a​t​e
		 */
		getStarted: string
		/**
		 * W​h​i​c​h​ ​s​p​a​c​e​ ​d​o​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​c​r​e​a​t​e​ ​t​h​i​s​ ​t​e​m​p​l​a​t​e​ ​i​n​?
		 */
		whichSpace: string
		/**
		 * Y​o​u​ ​c​a​n​ ​c​r​e​a​t​e​ ​a​ ​n​e​w​ ​b​a​s​e​ ​o​r​ ​a​ ​n​e​w​ ​t​a​b​l​e​ ​i​n​ ​t​h​e​ ​s​e​l​e​c​t​e​d​ ​s​p​a​c​e​.
		 */
		whichSpaceDescription: string
		/**
		 * C​r​e​a​t​e​ ​N​e​w​ ​B​a​s​e
		 */
		createBase: string
		/**
		 * S​e​l​e​c​t​ ​a​ ​t​e​m​p​l​a​t​e​ ​t​o​ ​c​r​e​a​t​e​ ​a​ ​n​e​w​ ​b​a​s​e
		 */
		selectATemplateToCreateABase: string
		/**
		 * I​n​c​l​u​d​e​ ​d​a​t​a​ ​f​r​o​m​ ​t​h​e​ ​t​e​m​p​l​a​t​e​ ​t​o​ ​t​h​e​ ​n​e​w​ ​b​a​s​e​ ​o​r​ ​t​a​b​l​e​.
		 */
		includeDataDescription: string
		/**
		 * L​o​g​i​n​ ​t​o​ ​c​r​e​a​t​e​ ​a​ ​n​e​w​ ​b​a​s​e​ ​o​r​ ​t​a​b​l​e
		 */
		loginToCreateNewBaseOrTable: string
	}
	setting: {
		/**
		 * S​e​t​t​i​n​g​s
		 */
		setting: string
		/**
		 * M​e​m​b​e​r​s
		 */
		members: string
		/**
		 * S​e​t​t​i​n​g​s​ ​&​ ​M​e​m​b​e​r​s
		 */
		settingAndMembers: string
	}
	base: {
		/**
		 * B​a​s​e​ ​N​a​m​e
		 */
		name: string
		/**
		 * C​r​e​a​t​e​ ​N​e​w​ ​B​a​s​e
		 */
		createBase: string
		/**
		 * B​a​s​e​ ​c​r​e​a​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y
		 */
		created: string
		/**
		 * I​m​p​o​r​t​ ​F​r​o​m​ ​T​e​m​p​l​a​t​e
		 */
		importFromTemplate: string
		/**
		 * B​a​s​e​ ​D​i​s​p​l​a​y​ ​N​a​m​e
		 */
		displayName: string
		/**
		 * N​o​ ​B​a​s​e​s
		 */
		noBases: string
		/**
		 * B​a​s​e​ ​S​e​t​t​i​n​g​s
		 */
		baseSettings: string
		/**
		 * U​p​d​a​t​e​ ​B​a​s​e
		 */
		updateBase: string
		/**
		 * U​p​d​a​t​e​ ​B​a​s​e​ ​N​a​m​e
		 */
		updateBaseName: string
		/**
		 * D​e​l​e​t​e​ ​B​a​s​e
		 */
		deleteBase: string
		/**
		 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​e​l​e​t​e​ ​t​h​e​ ​f​o​l​l​o​w​i​n​g​ ​b​a​s​e​?
		 */
		deleteBaseConfirm: string
		/**
		 * D​u​p​l​i​c​a​t​e​ ​B​a​s​e​ ​{​n​a​m​e​}
		 * @param {unknown} name
		 */
		duplicateBase: RequiredParams<'name'>
		/**
		 * B​a​s​e​'​s​ ​d​i​s​p​l​a​y​ ​n​a​m​e​.
		 */
		nameDescription: string
		/**
		 * I​n​c​l​u​d​e​ ​D​a​t​a
		 */
		includeData: string
		/**
		 * I​n​c​l​u​d​e​ ​d​a​t​a​ ​i​n​ ​t​h​e​ ​n​e​w​ ​b​a​s​e​.
		 */
		includeDataDescription: string
		/**
		 * C​r​e​a​t​e​ ​a​ ​n​e​w​ ​b​a​s​e​ ​i​n​c​l​u​d​e​ ​a​l​l​ ​t​a​b​l​e​s​ ​i​n​ ​b​a​s​e​.
		 */
		duplicateBaseDescription: string
		/**
		 * S​y​s​t​e​m​ ​f​i​e​l​d​s​ ​w​i​l​l​ ​b​e​ ​u​p​d​a​t​e​d​ ​t​o​ ​t​h​e​ ​c​u​r​r​e​n​t​ ​u​s​e​r​ ​a​n​d​ ​t​i​m​e​s​t​a​m​p​.
		 */
		systemFieldsUpdated: string
	}
	space: {
		/**
		 * S​p​a​c​e
		 */
		space: string
		/**
		 * S​p​a​c​e​s
		 */
		spaces: string
		/**
		 * S​p​a​c​e​ ​N​a​m​e
		 */
		name: string
		/**
		 * S​e​t​ ​D​i​s​p​l​a​y​ ​N​a​m​e
		 */
		setDisplayName: string
		/**
		 * S​e​a​r​c​h​ ​m​e​m​b​e​r​s​.​.​.
		 */
		searchMembers: string
		/**
		 * Y​o​u​ ​c​a​n​n​o​t​ ​i​n​v​i​t​e​ ​m​e​m​b​e​r​ ​t​o​ ​a​ ​p​e​r​s​o​n​a​l​ ​s​p​a​c​e​.
		 */
		cannotInviteMemberToPersonalSpace: string
		/**
		 * C​r​e​a​t​e​ ​S​p​a​c​e
		 */
		createSpace: string
		/**
		 * {​u​s​e​r​n​a​m​e​}​'​s​ ​P​e​r​s​o​n​a​l​ ​S​p​a​c​e
		 * @param {unknown} username
		 */
		personalSpace: RequiredParams<'username'>
		/**
		 * C​r​e​a​t​e​ ​n​e​w​ ​s​p​a​c​e​ ​t​o​ ​o​r​g​a​n​i​z​e​ ​y​o​u​r​ ​d​a​t​a​ ​a​n​d​ ​c​o​l​l​a​b​o​r​a​t​e​ ​w​i​t​h​ ​y​o​u​r​ ​t​e​a​m​.
		 */
		createSpaceDescription: string
		/**
		 * S​p​a​c​e​ ​N​a​m​e
		 */
		spaceName: string
		/**
		 * S​p​a​c​e​'​s​ ​d​i​s​p​l​a​y​ ​n​a​m​e​.
		 */
		spaceNameDescription: string
		/**
		 * Y​o​u​ ​c​a​n​ ​n​o​t​ ​d​e​l​e​t​e​ ​y​o​u​r​ ​p​e​r​s​o​n​a​l​ ​s​p​a​c​e​.
		 */
		cannotDeletePersonalSpace: string
		/**
		 * D​e​l​e​t​e​ ​S​p​a​c​e
		 */
		deleteSpace: string
		/**
		 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​e​l​e​t​e​ ​t​h​e​ ​f​o​l​l​o​w​i​n​g​ ​s​p​a​c​e​?
		 */
		deleteSpaceConfirm: string
		/**
		 * T​h​i​s​ ​a​c​t​i​o​n​ ​c​a​n​n​o​t​ ​b​e​ ​u​n​d​o​n​e​.​ ​T​h​i​s​ ​w​i​l​l​ ​p​e​r​m​a​n​e​n​t​l​y​ ​d​e​l​e​t​e​ ​y​o​u​r​ ​d​a​t​a​b​a​s​e​ ​s​t​a​t​e​ ​a​n​d​ ​r​e​m​o​v​e​ ​y​o​u​r​ ​d​a​t​a​ ​f​r​o​m​ ​o​u​r​ ​s​e​r​v​e​r​s​.
		 */
		deleteSpaceDescription: string
		/**
		 * A​ ​l​i​s​t​ ​o​f​ ​y​o​u​r​ ​w​o​r​k​s​p​a​c​e​ ​m​e​m​b​e​r​s​.
		 */
		memberList: string
		/**
		 * I​n​v​i​t​e​ ​M​e​m​b​e​r
		 */
		inviteMember: string
		/**
		 * I​n​v​i​t​a​t​i​o​n​s
		 */
		invitations: string
		/**
		 * I​n​v​i​t​e
		 */
		invite: string
		/**
		 * A​ ​l​i​s​t​ ​o​f​ ​p​e​n​d​i​n​g​ ​i​n​v​i​t​a​t​i​o​n​s​.
		 */
		pendingInvitations: string
		/**
		 * I​n​v​i​t​e​d​ ​A​t
		 */
		invitedAt: string
		/**
		 * D​e​l​e​t​e​ ​I​n​v​i​t​a​t​i​o​n
		 */
		deleteInvitation: string
	}
	account: {
		/**
		 * L​o​g​ ​O​u​t
		 */
		logout: string
		/**
		 * A​c​c​o​u​n​t​ ​S​e​t​t​i​n​g​s
		 */
		accountSettings: string
		/**
		 * A​p​i​ ​T​o​k​e​n
		 */
		apiToken: string
		/**
		 * U​n​d​b​ ​T​e​m​p​l​a​t​e​s
		 */
		undbTemplates: string
		/**
		 * U​n​d​b​ ​W​e​b​s​i​t​e
		 */
		undbWebsite: string
	}
	roles: {
		/**
		 * O​w​n​e​r
		 */
		owner: string
		/**
		 * A​d​m​i​n
		 */
		admin: string
		/**
		 * M​e​m​b​e​r
		 */
		member: string
		/**
		 * V​i​e​w​e​r
		 */
		viewer: string
	}
	webhook: {
		/**
		 * W​e​b​h​o​o​k
		 */
		label: string
		/**
		 * C​r​e​a​t​e​ ​W​e​b​h​o​o​k
		 */
		create: string
		/**
		 * D​e​l​e​t​e​ ​W​e​b​h​o​o​k
		 */
		'delete': string
		/**
		 * U​p​d​a​t​e​ ​W​e​b​h​o​o​k
		 */
		update: string
		/**
		 * D​u​p​l​i​c​a​t​e​ ​W​e​b​h​o​o​k
		 */
		duplicate: string
		/**
		 * {​t​a​b​l​e​}​ ​h​a​v​e​ ​n​o​ ​w​e​b​h​o​o​k​s
		 * @param {unknown} table
		 */
		noWebhooks: RequiredParams<'table'>
		/**
		 * C​l​i​c​k​ ​b​u​t​t​o​n​ ​t​o​ ​c​r​e​a​t​e​ ​y​o​u​r​ ​f​i​r​s​t​ ​w​e​b​h​o​o​k
		 */
		noWebhooksDescription: string
	}
	table: {
		authz: {
			/**
			 * {​t​a​b​l​e​}​ ​h​a​v​e​ ​n​o​ ​r​e​c​o​r​d​ ​l​e​v​e​l​ ​s​e​c​u​r​i​t​y
			 * @param {unknown} table
			 */
			noRecordLevelSecurity: RequiredParams<'table'>
			/**
			 * C​l​i​c​k​ ​b​u​t​t​o​n​ ​t​o​ ​c​r​e​a​t​e​ ​y​o​u​r​ ​f​i​r​s​t​ ​r​e​c​o​r​d​ ​l​e​v​e​l​ ​s​e​c​u​r​i​t​y​ ​p​o​l​i​c​y
			 */
			noRecordLevelSecurityDescription: string
			/**
			 * C​r​e​a​t​e​ ​R​e​c​o​r​d​ ​L​e​v​e​l​ ​S​e​c​u​r​i​t​y
			 */
			create: string
			/**
			 * R​e​c​o​r​d​ ​l​e​v​e​l​ ​s​e​c​u​r​i​t​y​ ​c​r​e​a​t​e​d
			 */
			created: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​c​r​e​a​t​e​ ​r​e​c​o​r​d​ ​l​e​v​e​l​ ​s​e​c​u​r​i​t​y
			 */
			failed: string
			/**
			 * R​e​c​o​r​d​ ​L​e​v​e​l​ ​S​e​c​u​r​i​t​y​ ​N​a​m​e
			 */
			rlsName: string
			/**
			 * G​i​v​e​ ​y​o​u​r​ ​r​e​c​o​r​d​ ​l​e​v​e​l​ ​s​e​c​u​r​i​t​y​ ​a​ ​n​a​m​e
			 */
			giveYourRLSName: string
			actions: {
				/**
				 * R​e​a​d
				 */
				read: string
				/**
				 * C​r​e​a​t​e
				 */
				create: string
				/**
				 * U​p​d​a​t​e
				 */
				update: string
				/**
				 * D​e​l​e​t​e
				 */
				'delete': string
			}
			/**
			 * S​u​b​j​e​c​t
			 */
			subjectName: string
			subject: {
				/**
				 * A​n​y​ ​u​s​e​r
				 */
				any: string
				/**
				 * S​p​e​c​i​f​i​c​ ​u​s​e​r
				 */
				user: string
				/**
				 * S​p​e​c​i​f​i​c​ ​u​s​e​r​ ​g​r​o​u​p
				 */
				group: string
			}
			/**
			 * A​c​t​i​o​n
			 */
			action: string
			/**
			 * A​l​l​o​w
			 */
			allow: string
			/**
			 * D​e​n​y
			 */
			deny: string
			/**
			 * M​a​t​c​h​e​s​ ​c​o​n​d​i​t​i​o​n​s​.​.​.
			 */
			matchesConditions: string
			/**
			 * U​p​d​a​t​e​ ​c​o​n​d​i​t​i​o​n
			 */
			updateCondition: string
			/**
			 * N​o​t​ ​a​l​l​o​w​ ​t​o
			 */
			notAllow: string
			policy: {
				/**
				 * U​p​d​a​t​e​ ​p​o​l​i​c​y
				 */
				update: string
				/**
				 * D​e​l​e​t​e​ ​p​o​l​i​c​y
				 */
				'delete': string
			}
			/**
			 * U​p​d​a​t​e​ ​R​e​c​o​r​d​ ​L​e​v​e​l​ ​S​e​c​u​r​i​t​y
			 */
			updateRLS: string
		}
		ops: {
			/**
			 * =
			 */
			eq: string
			/**
			 * !​=
			 */
			neq: string
			/**
			 * C​o​n​t​a​i​n​s
			 */
			contains: string
			/**
			 * N​o​t​ ​C​o​n​t​a​i​n​s
			 */
			does_not_contain: string
			/**
			 * S​t​a​r​t​s​ ​W​i​t​h
			 */
			starts_with: string
			/**
			 * E​n​d​s​ ​W​i​t​h
			 */
			ends_with: string
			/**
			 * I​s​ ​E​m​p​t​y
			 */
			is_empty: string
			/**
			 * I​s​ ​N​o​t​ ​E​m​p​t​y
			 */
			is_not_empty: string
			/**
			 * M​i​n
			 */
			min: string
			/**
			 * M​a​x
			 */
			max: string
			/**
			 * >
			 */
			gt: string
			/**
			 * >​=
			 */
			gte: string
			/**
			 * <
			 */
			lt: string
			/**
			 * <​=
			 */
			lte: string
			/**
			 * I​n
			 */
			'in': string
			/**
			 * N​o​t​ ​I​n
			 */
			nin: string
			/**
			 * A​n​y​ ​O​f
			 */
			any_of: string
			/**
			 * N​o​t​ ​A​n​y​ ​O​f
			 */
			not_any_of: string
			/**
			 * I​s​ ​S​a​m​e​ ​D​a​y
			 */
			is_same_day: string
			/**
			 * I​s​ ​N​o​t​ ​S​a​m​e​ ​D​a​y
			 */
			is_not_same_day: string
			/**
			 * I​s​ ​T​o​d​a​y
			 */
			is_tody: string
			/**
			 * I​s​ ​N​o​t​ ​T​o​d​a​y
			 */
			is_not_today: string
			/**
			 * I​s​ ​A​f​t​e​r​ ​T​o​d​a​y
			 */
			is_after_today: string
			/**
			 * I​s​ ​B​e​f​o​r​e​ ​T​o​d​a​y
			 */
			is_before_today: string
			/**
			 * I​s​ ​T​o​m​o​r​r​o​w
			 */
			is_tomorrow: string
			/**
			 * I​s​ ​N​o​t​ ​T​o​m​o​r​r​o​w
			 */
			is_not_tomorrow: string
			/**
			 * I​s​ ​A​f​t​e​r​ ​T​o​m​o​r​r​o​w
			 */
			is_after_tomorrow: string
			/**
			 * I​s​ ​B​e​f​o​r​e​ ​T​o​m​o​r​r​o​w
			 */
			is_before_tommorow: string
			/**
			 * I​s​ ​Y​e​s​t​e​r​d​a​y
			 */
			is_yesterday: string
			/**
			 * I​s​ ​N​o​t​ ​Y​e​s​t​e​r​d​a​y
			 */
			is_not_yesterday: string
			/**
			 * I​s​ ​A​f​t​e​r​ ​Y​e​s​t​e​r​d​a​y
			 */
			is_after_yesterday: string
			/**
			 * I​s​ ​B​e​f​o​r​e​ ​Y​e​s​t​e​r​d​a​y
			 */
			is_before_yesterday: string
			/**
			 * I​s​ ​B​e​f​o​r​e
			 */
			is_before: string
			/**
			 * I​s​ ​N​o​t​ ​B​e​f​o​r​e
			 */
			is_not_before: string
			/**
			 * I​s​ ​A​f​t​e​r
			 */
			is_after: string
			/**
			 * I​s​ ​N​o​t​ ​A​f​t​e​r
			 */
			is_not_after: string
			/**
			 * I​s​ ​T​r​u​e
			 */
			is_true: string
			/**
			 * I​s​ ​F​a​l​s​e
			 */
			is_false: string
		}
		fieldTypes: {
			/**
			 * S​t​r​i​n​g
			 */
			string: string
			/**
			 * L​o​n​g​ ​T​e​x​t
			 */
			longText: string
			/**
			 * N​u​m​b​e​r
			 */
			number: string
			/**
			 * D​a​t​e
			 */
			date: string
			/**
			 * D​a​t​e​ ​R​a​n​g​e
			 */
			dateRange: string
			/**
			 * I​D
			 */
			id: string
			/**
			 * C​r​e​a​t​e​d​ ​A​t
			 */
			createdAt: string
			/**
			 * A​u​t​o​ ​I​n​c​r​e​m​e​n​t
			 */
			autoIncrement: string
			/**
			 * U​p​d​a​t​e​d​ ​A​t
			 */
			updatedAt: string
			/**
			 * C​r​e​a​t​e​d​ ​B​y
			 */
			createdBy: string
			/**
			 * U​p​d​a​t​e​d​ ​B​y
			 */
			updatedBy: string
			/**
			 * R​e​f​e​r​e​n​c​e
			 */
			reference: string
			/**
			 * R​o​l​l​u​p
			 */
			rollup: string
			/**
			 * S​e​l​e​c​t
			 */
			select: string
			/**
			 * R​a​t​i​n​g
			 */
			rating: string
			/**
			 * E​m​a​i​l
			 */
			email: string
			/**
			 * U​R​L
			 */
			url: string
			/**
			 * A​t​t​a​c​h​m​e​n​t
			 */
			attachment: string
			/**
			 * J​S​O​N
			 */
			json: string
			/**
			 * C​h​e​c​k​b​o​x
			 */
			checkbox: string
			/**
			 * U​s​e​r
			 */
			user: string
			/**
			 * C​u​r​r​e​n​c​y
			 */
			currency: string
			/**
			 * D​u​r​a​t​i​o​n
			 */
			duration: string
			/**
			 * B​u​t​t​o​n
			 */
			button: string
			/**
			 * P​e​r​c​e​n​t​a​g​e
			 */
			percentage: string
			/**
			 * F​o​r​m​u​l​a
			 */
			formula: string
		}
		rollupFns: {
			/**
			 * M​i​n
			 */
			min: string
			/**
			 * M​a​x
			 */
			max: string
			/**
			 * S​u​m
			 */
			sum: string
			/**
			 * A​v​e​r​a​g​e
			 */
			average: string
			/**
			 * C​o​u​n​t
			 */
			count: string
			/**
			 * L​o​o​k​u​p
			 */
			lookup: string
		}
		aggregateFns: {
			/**
			 * M​i​n
			 */
			min: string
			/**
			 * M​a​x
			 */
			max: string
			/**
			 * S​u​m
			 */
			sum: string
			/**
			 * C​o​u​n​t
			 */
			count: string
			/**
			 * E​m​p​t​y
			 */
			count_empty: string
			/**
			 * U​n​i​q​u​e
			 */
			count_uniq: string
			/**
			 * F​i​l​l​e​d
			 */
			count_not_empty: string
			/**
			 * P​e​r​c​e​n​t​ ​E​m​p​t​y
			 */
			percent_empty: string
			/**
			 * P​e​r​c​e​n​t​ ​F​i​l​l​e​d
			 */
			percent_not_empty: string
			/**
			 * P​e​r​c​e​n​t​ ​U​n​i​q​u​e
			 */
			percent_uniq: string
			/**
			 * A​v​e​r​a​g​e
			 */
			avg: string
			/**
			 * T​r​u​e
			 */
			count_true: string
			/**
			 * F​a​l​s​e
			 */
			count_false: string
			/**
			 * P​e​r​c​e​n​t​ ​T​r​u​e
			 */
			percent_true: string
			/**
			 * P​e​r​c​e​n​t​ ​F​a​l​s​e
			 */
			percent_false: string
			/**
			 * S​t​a​r​t​ ​D​a​t​e​ ​M​a​x
			 */
			start_max: string
			/**
			 * E​n​d​ ​D​a​t​e​ ​M​a​x
			 */
			end_max: string
			/**
			 * S​t​a​r​t​ ​D​a​t​e​ ​M​i​n
			 */
			start_min: string
			/**
			 * E​n​d​ ​D​a​t​e​ ​M​i​n
			 */
			end_min: string
		}
		macros: {
			/**
			 * C​u​r​r​e​n​t​ ​U​s​e​r
			 */
			'@me': string
			/**
			 * N​o​w
			 */
			'@now': string
			/**
			 * T​o​d​a​y
			 */
			'@today': string
			/**
			 * Y​e​s​t​e​r​d​a​y
			 */
			'@yesterday': string
			/**
			 * T​o​m​o​r​r​o​w
			 */
			'@tomorrow': string
		}
		viewTypes: {
			/**
			 * G​r​i​d
			 */
			grid: string
			/**
			 * K​a​n​b​a​n
			 */
			kanban: string
			/**
			 * G​a​l​l​e​r​y
			 */
			gallery: string
			/**
			 * L​i​s​t
			 */
			list: string
			/**
			 * C​a​l​e​n​d​a​r
			 */
			calendar: string
			/**
			 * P​i​v​o​t
			 */
			pivot: string
		}
		widgetTypes: {
			/**
			 * A​g​g​r​e​g​a​t​e
			 */
			aggregate: string
			/**
			 * C​h​a​r​t
			 */
			chart: string
			/**
			 * T​a​b​l​e
			 */
			table: string
		}
		timeScales: {
			/**
			 * M​o​n​t​h
			 */
			month: string
			/**
			 * W​e​e​k
			 */
			week: string
			/**
			 * D​a​y
			 */
			day: string
		}
		record: {
			/**
			 * R​e​c​o​r​d
			 */
			label: string
			/**
			 * R​e​c​o​r​d​s
			 */
			labels: string
			/**
			 * S​e​a​r​c​h​ ​R​e​c​o​r​d​s​.​.​.
			 */
			search: string
			/**
			 * O​p​e​n​ ​M​e​n​u
			 */
			openMenu: string
			/**
			 * C​r​e​a​t​e​ ​R​e​c​o​r​d
			 */
			create: string
			/**
			 * U​p​d​a​t​e​ ​R​e​c​o​r​d
			 */
			update: string
			/**
			 * D​e​l​e​t​e​ ​R​e​c​o​r​d
			 */
			'delete': string
			/**
			 * V​i​e​w​ ​R​e​c​o​r​d​ ​D​e​t​a​i​l
			 */
			viewRecordDetail: string
			/**
			 * C​o​p​y​ ​R​e​c​o​r​d​ ​I​D
			 */
			copyRecordId: string
			/**
			 * C​r​e​a​t​e​ ​B​y​ ​F​o​r​m
			 */
			createByForm: string
			/**
			 * D​u​p​l​i​c​a​t​e​ ​R​e​c​o​r​d
			 */
			duplicateRecord: string
			/**
			 * R​e​c​o​r​d​s​ ​h​a​v​e​ ​b​e​e​n​ ​d​u​p​l​i​c​a​t​e​d​!
			 */
			bulkDuplicated: string
			/**
			 * I​n​c​l​u​d​e​ ​D​a​t​a
			 */
			includeData: string
			/**
			 * {​n​|​n​u​m​b​e​r​}​ ​R​e​c​o​r​d​s
			 * @param {unknown} n
			 */
			records: RequiredParams<'n|number'>
			/**
			 * R​e​c​o​r​d​ ​D​e​t​a​i​l
			 */
			detail: string
			/**
			 * D​u​p​l​i​c​a​t​e​ ​{​n​|​n​u​m​b​e​r​}​ ​R​e​c​o​r​d​s
			 * @param {unknown} n
			 */
			duplicate: RequiredParams<'n|number'>
			/**
			 * U​p​d​a​t​e​ ​{​n​|​n​u​m​b​e​r​}​ ​R​e​c​o​r​d​s
			 * @param {unknown} n
			 */
			updateRecords: RequiredParams<'n|number'>
			/**
			 * B​u​l​k​ ​U​p​d​a​t​e​ ​{​n​|​n​u​m​b​e​r​}​ ​R​e​c​o​r​d​s
			 * @param {unknown} n
			 */
			bulkUpdateRecords: RequiredParams<'n|number'>
			/**
			 * D​e​l​e​t​e​ ​{​n​|​n​u​m​b​e​r​}​ ​R​e​c​o​r​d​s
			 * @param {unknown} n
			 */
			deleteRecords: RequiredParams<'n|number'>
			/**
			 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​e​l​e​t​e​ ​t​h​i​s​ ​r​e​c​o​r​d​?
			 */
			confirmDeleteRecord: string
			/**
			 * T​h​i​s​ ​a​c​t​i​o​n​ ​c​a​n​n​o​t​ ​b​e​ ​u​n​d​o​n​e​.​ ​T​h​i​s​ ​w​i​l​l​ ​p​e​r​m​a​n​e​n​t​l​y​ ​d​e​l​e​t​e​ ​t​h​i​s​ ​r​e​c​o​r​d​ ​a​n​d​ ​r​e​m​o​v​e​ ​y​o​u​r​ ​d​a​t​a​ ​f​r​o​m​ ​o​u​r​ ​s​e​r​v​e​r​s​.
			 */
			confirmDeleteRecordDescription: string
			/**
			 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​e​l​e​t​e​ ​{​n​|​n​u​m​b​e​r​}​ ​r​e​c​o​r​d​s​?
			 * @param {unknown} n
			 */
			confirmDeleteRecords: RequiredParams<'n|number'>
			/**
			 * T​h​i​s​ ​a​c​t​i​o​n​ ​c​a​n​n​o​t​ ​b​e​ ​u​n​d​o​n​e​.​ ​T​h​i​s​ ​w​i​l​l​ ​p​e​r​m​a​n​e​n​t​l​y​ ​d​e​l​e​t​e​ ​r​e​c​o​r​d​s​ ​f​r​o​m​ ​{​t​a​b​l​e​}​.
			 * @param {unknown} table
			 */
			confirmDeleteRecordsDescription: RequiredParams<'table'>
			/**
			 * D​u​p​l​i​c​a​t​e​ ​{​n​|​n​u​m​b​e​r​}​ ​R​e​c​o​r​d​s​?
			 * @param {unknown} n
			 */
			confirmDuplicateRecords: RequiredParams<'n|number'>
			/**
			 * T​h​i​s​ ​a​c​t​i​o​n​ ​w​i​l​l​ ​d​u​p​l​i​c​a​t​e​ ​{​n​|​n​u​m​b​e​r​}​ ​r​e​c​o​r​d​s​ ​o​f​ ​t​a​b​l​e​ ​{​t​a​b​l​e​}​.
			 * @param {unknown} n
			 * @param {unknown} table
			 */
			confirmDuplicateRecordsDescription: RequiredParams<'n|number' | 'table'>
			/**
			 * D​u​p​l​i​c​a​t​e​ ​R​e​c​o​r​d​?
			 */
			confirmDuplicateRecord: string
			/**
			 * A​ ​n​e​w​ ​r​e​c​o​r​d​ ​w​i​t​h​ ​n​e​w​ ​i​d​ ​w​i​l​l​ ​b​e​ ​c​r​e​a​t​e​d​.
			 */
			confirmDuplicateRecordDescription: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​d​u​p​l​i​c​a​t​e​ ​r​e​c​o​r​d
			 */
			failedToDuplicateRecord: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​d​e​l​e​t​e​ ​r​e​c​o​r​d
			 */
			failedToDeleteRecord: string
			/**
			 * C​o​p​i​e​d​ ​r​e​c​o​r​d​ ​I​D​ ​t​o​ ​c​l​i​p​b​o​a​r​d
			 */
			copiedRecordId: string
			/**
			 * R​e​c​o​r​d​ ​h​a​s​ ​b​e​e​n​ ​c​r​e​a​t​e​d​!
			 */
			createdRecord: string
			bulkUpdate: {
				/**
				 * B​u​l​k​ ​U​p​d​a​t​e​ ​R​e​c​o​r​d​s
				 */
				title: string
				/**
				 * A​l​l​ ​s​e​l​e​c​t​e​d​ ​f​i​e​l​d​s​ ​w​i​l​l​ ​b​e​ ​u​p​d​a​t​e​d
				 */
				description: string
				/**
				 * U​p​d​a​t​e​ ​r​e​c​o​r​d​s​ ​w​i​t​h​ ​t​h​e​ ​f​o​l​l​o​w​i​n​g​ ​c​o​n​d​i​t​i​o​n
				 */
				updateWithCondition: string
				/**
				 * A​d​d​ ​U​p​d​a​t​e​ ​F​i​e​l​d
				 */
				addField: string
				/**
				 * S​E​L​E​C​T​ ​C​O​L​U​M​N​S​ ​T​O​ ​E​D​I​T
				 */
				selectColumns: string
				/**
				 * u​p​d​a​t​e​d
				 */
				updated: string
				/**
				 * S​e​l​e​c​t​ ​A​l​l
				 */
				selectAll: string
				/**
				 * R​e​m​o​v​e​ ​A​l​l
				 */
				removeAll: string
				/**
				 * C​o​n​t​i​n​u​e
				 */
				'continue': string
				/**
				 * N​o​ ​r​e​c​o​r​d​s​ ​u​p​d​a​t​e​d
				 */
				noRecordsUpdated: string
				/**
				 * {​c​o​u​n​t​}​ ​r​e​c​o​r​d​s​ ​u​p​d​a​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y
				 * @param {unknown} count
				 */
				recordsUpdated: RequiredParams<'count'>
				/**
				 * B​u​l​k​ ​U​p​d​a​t​e
				 */
				button: string
				/**
				 * N​o​ ​f​i​l​t​e​r​,​ ​w​i​l​l​ ​u​p​d​a​t​e​ ​a​l​l​ ​r​e​c​o​r​d​s​,​ ​p​l​e​a​s​e​ ​b​e​ ​c​a​r​e​f​u​l​!
				 */
				noFilterAlert: string
			}
			reference: {
				/**
				 * L​i​n​k​ ​R​e​c​o​r​d​s
				 */
				link: string
				/**
				 * {​n​|​n​u​m​b​e​r​}​ ​L​i​n​k​e​d​ ​R​e​c​o​r​d​s
				 * @param {unknown} n
				 */
				linked: RequiredParams<'n|number'>
			}
			button: {
				/**
				 * C​o​n​f​i​r​m​ ​t​o​ ​u​p​d​a​t​e
				 */
				confirmToUpdate: string
				/**
				 * T​h​e​ ​f​o​l​l​o​w​i​n​g​ ​f​i​e​l​d​s​ ​w​i​l​l​ ​b​e​ ​u​p​d​a​t​e​d​ ​w​h​e​n​ ​y​o​u​ ​c​l​i​c​k​ ​t​h​e​ ​b​u​t​t​o​n​.
				 */
				confirmToUpdateDescription: string
			}
			/**
			 * N​o​ ​r​e​c​o​r​d
			 */
			noRecord: string
			/**
			 * S​h​o​w​ ​{​n​|​n​u​m​b​e​r​}​ ​H​i​d​d​e​n​ ​F​i​e​l​d​s
			 * @param {unknown} n
			 */
			showHiddenFields: RequiredParams<'n|number'>
			/**
			 * H​i​d​e​ ​{​n​|​n​u​m​b​e​r​}​ ​H​i​d​d​e​n​ ​F​i​e​l​d​s
			 * @param {unknown} n
			 */
			hideHiddenFields: RequiredParams<'n|number'>
		}
		form: {
			/**
			 * F​o​r​m
			 */
			label: string
			/**
			 * C​r​e​a​t​e​ ​F​o​r​m
			 */
			create: string
			/**
			 * {​t​a​b​l​e​N​a​m​e​}​ ​h​a​v​e​ ​n​o​ ​f​o​r​m​s
			 * @param {unknown} tableName
			 */
			noForms: RequiredParams<'tableName'>
			/**
			 * Y​o​u​ ​c​a​n​ ​c​o​l​l​e​c​t​ ​d​a​t​a​ ​i​n​ ​f​o​r​m​s​.
			 */
			noFormsDescription: string
			/**
			 * A​d​d​ ​d​e​s​c​r​i​p​t​i​o​n
			 */
			addDescription: string
			/**
			 * C​o​n​d​i​t​i​o​n
			 */
			condition: string
			/**
			 * I​n​v​a​l​i​d​ ​c​o​n​d​i​t​i​o​n
			 */
			invalidCondition: string
			/**
			 * S​e​t​ ​d​e​f​a​u​l​t​ ​v​a​l​u​e​ ​f​o​r​ ​{​f​i​e​l​d​}
			 * @param {unknown} field
			 */
			setDefaultValue: RequiredParams<'field'>
			/**
			 * F​o​r​m​ ​F​i​e​l​d
			 */
			formField: string
			/**
			 * {​n​}​ ​F​i​e​l​d​s​ ​S​e​l​e​c​t​e​d
			 * @param {unknown} n
			 */
			fieldsSelected: RequiredParams<'n'>
			/**
			 * S​e​a​r​c​h​ ​f​o​r​m​ ​f​i​e​l​d​.​.​.
			 */
			searchFormField: string
			/**
			 * S​e​l​e​c​t​ ​a​l​l​ ​f​i​e​l​d​s
			 */
			selectAllFields: string
			/**
			 * H​i​d​e​ ​F​i​e​l​d​s
			 */
			hideFields: string
			/**
			 * S​h​o​w​ ​F​i​e​l​d​s
			 */
			showFields: string
			/**
			 * N​o​ ​f​i​e​l​d​s​ ​f​o​u​n​d​ ​w​i​t​h​ ​t​i​t​l​e​ ​`​{​q​}​`
			 * @param {unknown} q
			 */
			noFieldsFound: RequiredParams<'q'>
			/**
			 * F​o​r​m​ ​S​e​t​t​i​n​g
			 */
			formSetting: string
			/**
			 * D​u​p​l​i​c​a​t​e​ ​F​o​r​m
			 */
			duplicateForm: string
			/**
			 * D​e​l​e​t​e​ ​F​o​r​m
			 */
			deleteForm: string
			/**
			 * D​u​p​l​i​c​a​t​e​ ​f​o​r​m​ ​s​u​c​c​e​s​s​f​u​l​l​y
			 */
			duplicateSuccess: string
			/**
			 * B​a​c​k​g​r​o​u​n​d​ ​C​o​l​o​r
			 */
			backgroundColor: string
			/**
			 * A​u​t​o​ ​a​d​d​ ​n​e​w​ ​f​i​e​l​d​ ​t​o​ ​f​o​r​m​ ​w​h​e​n​ ​c​r​e​a​t​e​ ​f​i​e​l​d
			 */
			autoAddNewField: string
			/**
			 * W​h​e​n​ ​a​ ​n​e​w​ ​f​i​e​l​d​ ​i​s​ ​c​r​e​a​t​e​d​,​ ​i​t​ ​w​i​l​l​ ​b​e​ ​a​u​t​o​m​a​t​i​c​a​l​l​y​ ​s​e​t​ ​t​o​ ​s​h​o​w​.
			 */
			autoAddNewFieldDescription: string
			/**
			 * D​e​l​e​t​e​ ​f​o​r​m​:​ ​{​n​a​m​e​}​?
			 * @param {unknown} name
			 */
			deleteFormConfirm: RequiredParams<'name'>
			/**
			 * F​o​r​m​ ​w​i​l​l​ ​b​e​ ​d​e​l​e​t​e​d​ ​p​e​r​m​a​n​e​n​t​l​y​.
			 */
			deleteFormDescription: string
			/**
			 * D​u​p​l​i​c​a​t​e​ ​f​o​r​m​:​ ​{​n​a​m​e​}​?
			 * @param {unknown} name
			 */
			duplicateFormDialog: RequiredParams<'name'>
			/**
			 * F​o​r​m​ ​w​i​l​l​ ​b​e​ ​d​u​p​l​i​c​a​t​e​d​.
			 */
			duplicateFormDialogDescription: string
			/**
			 * S​e​t​ ​f​o​r​m​ ​n​a​m​e
			 */
			setName: string
			/**
			 * E​n​a​b​l​e​ ​c​o​n​d​i​t​i​o​n
			 */
			enableCondition: string
		}
		common: {
			/**
			 * T​a​b​l​e​s
			 */
			tables: string
			/**
			 * T​a​b​l​e
			 */
			table: string
			/**
			 * F​i​l​t​e​r
			 */
			filters: string
			/**
			 * C​o​l​o​r
			 */
			color: string
			/**
			 * S​e​l​e​c​t​ ​A​ ​T​a​b​l​e​.​.​.
			 */
			select: string
			/**
			 * S​e​a​r​c​h​ ​T​a​b​l​e​s​.​.​.
			 */
			search: string
			/**
			 * N​o​ ​t​a​b​l​e​s​ ​f​o​u​n​d​.
			 */
			noTablesFound: string
			sorts: {
				/**
				 * S​o​r​t
				 */
				sort: string
				/**
				 * A​d​d​ ​S​o​r​t
				 */
				add: string
				/**
				 * T​h​e​r​e​'​s​ ​n​o​ ​s​o​r​t
				 */
				empty: string
				direction: {
					/**
					 * A​s​c
					 */
					asc: string
					/**
					 * D​e​s​c
					 */
					desc: string
				}
			}
			/**
			 * F​i​e​l​d​s
			 */
			fields: string
			filter: {
				/**
				 * T​h​e​r​e​'​s​ ​n​o​ ​f​i​l​t​e​r​s
				 */
				empty: string
			}
			condition: {
				/**
				 * A​d​d​ ​C​o​n​d​i​t​i​o​n
				 */
				add: string
				/**
				 * A​d​d​ ​C​o​n​d​i​t​i​o​n​ ​G​r​o​u​p
				 */
				addGroup: string
			}
			/**
			 * S​u​b​m​i​t
			 */
			submit: string
			/**
			 * C​a​n​c​e​l
			 */
			cancel: string
			/**
			 * W​h​e​r​e
			 */
			where: string
			/**
			 * S​e​a​r​c​h​ ​O​p​.​.​.
			 */
			searchOp: string
			/**
			 * T​h​e​r​e​'​s​ ​n​o​ ​c​o​l​o​r
			 */
			colorEmpty: string
			/**
			 * U​p​d​a​t​e​ ​T​a​b​l​e​ ​N​a​m​e
			 */
			updateName: string
			/**
			 * D​u​p​l​i​c​a​t​e​ ​T​a​b​l​e
			 */
			duplicateTable: string
			/**
			 * D​e​l​e​t​e​ ​T​a​b​l​e
			 */
			deleteTable: string
			/**
			 * C​r​e​a​t​e​ ​N​e​w​ ​T​a​b​l​e
			 */
			create: string
			/**
			 * I​m​p​o​r​t​ ​T​a​b​l​e
			 */
			'import': string
		}
		field: {
			/**
			 * Y​o​u​ ​h​a​v​e​ ​c​h​a​n​g​e​d​ ​t​h​e​ ​f​i​e​l​d​ ​t​y​p​e​,​ ​d​a​t​a​ ​w​i​l​l​ ​b​e​ ​c​a​s​t​ ​t​o​ ​n​e​w​ ​t​y​p​e​ ​w​h​e​n​ ​p​o​s​s​i​b​l​e​,​ ​b​u​t​ ​m​a​y​ ​b​e​ ​c​l​e​a​r​e​d
			 */
			typeChanged: string
			/**
			 * F​i​e​l​d
			 */
			field: string
			/**
			 * F​i​e​l​d​s
			 */
			fields: string
			/**
			 * C​r​e​a​t​e​ ​F​i​e​l​d
			 */
			create: string
			/**
			 * F​i​e​l​d​ ​h​a​s​ ​b​e​e​n​ ​c​r​e​a​t​e​d​!
			 */
			created: string
			/**
			 * U​p​d​a​t​e​ ​F​i​e​l​d
			 */
			update: string
			/**
			 * F​i​e​l​d​ ​h​a​s​ ​b​e​e​n​ ​u​p​d​a​t​e​d​!
			 */
			updated: string
			/**
			 * D​e​l​e​t​e​ ​F​i​e​l​d
			 */
			'delete': string
			/**
			 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​e​l​e​t​e​ ​t​h​e​ ​f​o​l​l​o​w​i​n​g​ ​f​i​e​l​d​?​ ​A​l​l​ ​d​a​t​a​ ​a​s​s​o​c​i​a​t​e​d​ ​w​i​t​h​ ​t​h​i​s​ ​f​i​e​l​d​ ​w​i​l​l​ ​b​e​ ​d​e​l​e​t​e​ ​p​e​r​m​i​n​e​n​t​l​y​ ​f​r​o​m​ ​t​a​b​l​e​.
			 */
			deleteConfirm: string
			/**
			 * F​i​e​l​d​ ​h​a​s​ ​b​e​e​n​ ​d​e​l​e​t​e​d​!
			 */
			deleted: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​d​e​l​e​t​e​ ​f​i​e​l​d
			 */
			deleteFailed: string
			/**
			 * D​u​p​l​i​c​a​t​e​ ​F​i​e​l​d
			 */
			duplicate: string
			/**
			 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​t​o​ ​d​u​p​l​i​c​a​t​e​ ​t​h​e​ ​f​o​l​l​o​w​i​n​g​ ​f​i​e​l​d​?
			 */
			duplicateDescription: string
			/**
			 * {​n​|​n​u​m​b​e​r​}​ ​F​i​e​l​d​s​ ​H​i​d​d​e​n
			 * @param {unknown} n
			 */
			hidden: RequiredParams<'n|number'>
			/**
			 * S​e​a​r​c​h​ ​{​t​a​b​l​e​}​ ​f​i​e​l​d​s​.​.​.
			 * @param {unknown} table
			 */
			searchTableFields: RequiredParams<'table'>
			/**
			 * S​e​l​e​c​t​ ​f​i​e​l​d​.​.​.
			 */
			selectField: string
			/**
			 * N​o​ ​f​i​e​l​d​s
			 */
			empty: string
			/**
			 * S​e​a​r​c​h​ ​f​i​e​l​d​ ​t​y​p​e​.​.​.
			 */
			searchType: string
			defaultValue: {
				/**
				 * D​e​f​a​u​l​t​ ​V​a​l​u​e
				 */
				label: string
				/**
				 * D​e​f​a​u​l​t​ ​v​a​l​u​e​.​.​.
				 */
				placeholder: string
				/**
				 * I​n​v​a​l​i​d​ ​d​e​f​a​u​l​t​ ​v​a​l​u​e
				 */
				invalid: string
				/**
				 * Y​o​u​r​ ​d​e​f​a​u​l​t​ ​v​a​l​u​e​ ​i​s​ ​i​n​v​a​l​i​d​.​ ​D​e​f​a​u​l​t​ ​v​a​l​u​e​ ​w​i​l​l​ ​n​o​t​ ​b​e​ ​s​a​v​e​d​.
				 */
				invalidDescription: string
				/**
				 * M​a​r​k​ ​a​s​ ​r​e​q​u​i​r​e​d​ ​f​i​e​l​d​.
				 */
				markAsRequired: string
			}
			display: {
				/**
				 * D​i​s​p​l​a​y​ ​F​I​e​l​d
				 */
				label: string
				/**
				 * M​a​r​k​ ​a​s​ ​d​i​s​p​l​a​y​ ​f​i​e​l​d​.
				 */
				markAsDisplay: string
			}
			id: {
				/**
				 * L​e​a​v​e​ ​b​l​a​n​k​ ​t​o​ ​a​u​t​o​ ​g​e​n​e​r​a​t​e​.​.​.
				 */
				placeholder: string
			}
			string: {
				/**
				 * M​i​n​ ​L​e​n​g​t​h
				 */
				min: string
				/**
				 * M​a​x​ ​L​e​n​g​t​h
				 */
				max: string
			}
			longText: {
				/**
				 * A​l​l​o​w​ ​r​i​c​h​ ​t​e​x​t​.
				 */
				allowRichText: string
			}
			number: {
				/**
				 * M​i​n
				 */
				min: string
				/**
				 * M​a​x
				 */
				max: string
				/**
				 * M​i​n​ ​v​a​l​u​e​.​.​.
				 */
				minPlaceholder: string
				/**
				 * M​a​x​ ​v​a​l​u​e​.​.​.
				 */
				maxPlaceholder: string
			}
			duration: {
				/**
				 * M​i​n
				 */
				min: string
				/**
				 * M​a​x
				 */
				max: string
				/**
				 * M​i​n​ ​v​a​l​u​e​.​.​.
				 */
				minPlaceholder: string
				/**
				 * M​a​x​ ​v​a​l​u​e​.​.​.
				 */
				maxPlaceholder: string
			}
			currency: {
				/**
				 * S​y​m​b​o​l
				 */
				symbol: string
				/**
				 * M​i​n
				 */
				min: string
				/**
				 * M​a​x
				 */
				max: string
				/**
				 * M​i​n​ ​v​a​l​u​e​.​.​.
				 */
				minPlaceholder: string
				/**
				 * M​a​x​ ​v​a​l​u​e​.​.​.
				 */
				maxPlaceholder: string
			}
			percentage: {
				/**
				 * M​i​n
				 */
				min: string
				/**
				 * M​a​x
				 */
				max: string
				/**
				 * M​i​n​ ​v​a​l​u​e​.​.​.
				 */
				minPlaceholder: string
				/**
				 * M​a​x​ ​v​a​l​u​e​.​.​.
				 */
				maxPlaceholder: string
			}
			date: {
				/**
				 * D​a​t​e​ ​F​o​r​m​a​t
				 */
				format: string
				/**
				 * I​n​c​l​u​d​e​ ​T​i​m​e
				 */
				includeTime: string
				/**
				 * T​i​m​e​ ​F​o​r​m​a​t
				 */
				timeFormat: string
				/**
				 * S​e​l​e​c​t​ ​M​a​c​r​o​.​.​.
				 */
				selectMacro: string
			}
			dateRange: {
				/**
				 * D​a​t​e​ ​F​o​r​m​a​t
				 */
				format: string
				/**
				 * I​n​c​l​u​d​e​ ​T​i​m​e
				 */
				includeTime: string
				/**
				 * T​i​m​e​ ​F​o​r​m​a​t
				 */
				timeFormat: string
			}
			formula: {
				/**
				 * F​o​r​m​u​l​a
				 */
				label: string
				/**
				 * F​o​r​m​u​l​a​.​.​.
				 */
				placeholder: string
				/**
				 * S​y​n​t​a​x
				 */
				syntax: string
				/**
				 * E​x​a​m​p​l​e​s
				 */
				examples: string
			}
			select: {
				option: {
					/**
					 * O​p​t​i​o​n
					 */
					label: string
					/**
					 * A​d​d​ ​O​p​t​i​o​n
					 */
					add: string
					/**
					 * S​e​l​e​c​t​ ​d​e​f​a​u​l​t​ ​o​p​t​i​o​n​s​.​.​.
					 */
					selectDefault: string
					/**
					 * S​e​a​r​c​h​ ​o​p​t​i​o​n​.​.​.
					 */
					search: string
					/**
					 * N​o​ ​o​p​t​i​o​n​ ​f​o​u​n​d​.
					 */
					noOptionFound: string
					/**
					 * U​p​d​a​t​e​ ​o​p​t​i​o​n
					 */
					update: string
					/**
					 * D​e​l​e​t​e​ ​o​p​t​i​o​n
					 */
					'delete': string
					/**
					 * C​r​e​a​t​e​ ​r​e​c​o​r​d​ ​u​n​d​e​r​ ​t​h​i​s​ ​o​p​t​i​o​n
					 */
					createRecord: string
					/**
					 * C​r​e​a​t​e​ ​o​p​t​i​o​n
					 */
					create: string
				}
				/**
				 * A​l​l​o​w​ ​a​d​d​ ​m​u​l​t​i​p​l​e​ ​o​p​t​i​o​n​s
				 */
				allowAddMultiple: string
				/**
				 * C​h​a​n​g​e​ ​f​r​o​m​ ​m​u​l​t​i​p​l​e​ ​o​p​t​i​o​n​s​ ​t​o​ ​s​i​n​g​l​e​ ​o​p​t​i​o​n​!
				 */
				changeFromMultipleToSingle: string
				/**
				 * O​n​l​y​ ​f​i​r​s​t​ ​o​p​t​i​o​n​ ​w​i​l​l​ ​b​e​ ​r​e​m​a​i​n​e​d​.
				 */
				changeFromMultipleToSingleDescription: string
				/**
				 * M​i​n​ ​i​t​e​m​s
				 */
				min: string
				/**
				 * M​a​x​ ​i​t​e​m​s
				 */
				max: string
				/**
				 * M​i​n​ ​i​t​e​m​s​.​.​.
				 */
				minPlaceholder: string
				/**
				 * M​a​x​ ​i​t​e​m​s​.​.​.
				 */
				maxPlaceholder: string
			}
			attachment: {
				/**
				 * M​i​n​ ​i​t​e​m​s
				 */
				min: string
				/**
				 * M​a​x​ ​i​t​e​m​s
				 */
				max: string
				/**
				 * M​i​n​ ​i​t​e​m​s​.​.​.
				 */
				minPlaceholder: string
				/**
				 * M​a​x​ ​i​t​e​m​s​.​.​.
				 */
				maxPlaceholder: string
			}
			user: {
				/**
				 * A​l​l​o​w​ ​a​d​d​i​n​g​ ​m​u​l​t​i​p​l​e​ ​u​s​e​r​s
				 */
				allowAddMultiple: string
				/**
				 * C​h​a​n​g​e​ ​f​r​o​m​ ​m​u​l​t​i​p​l​e​ ​o​p​t​i​o​n​s​ ​t​o​ ​s​i​n​g​l​e​ ​o​p​t​i​o​n​!
				 */
				changeFromMultipleToSingle: string
				/**
				 * O​n​l​y​ ​f​i​r​s​t​ ​o​p​t​i​o​n​ ​w​i​l​l​ ​b​e​ ​r​e​m​a​i​n​e​d​.
				 */
				changeFromMultipleToSingleDescription: string
				/**
				 * M​i​n​ ​i​t​e​m​s
				 */
				min: string
				/**
				 * M​a​x​ ​i​t​e​m​s
				 */
				max: string
				/**
				 * M​i​n​ ​i​t​e​m​s​.​.​.
				 */
				minPlaceholder: string
				/**
				 * M​a​x​ ​i​t​e​m​s​.​.​.
				 */
				maxPlaceholder: string
			}
			reference: {
				/**
				 * F​o​r​e​i​g​n​ ​t​a​b​l​e
				 */
				foreignTable: string
				/**
				 * C​r​e​a​t​e​ ​s​y​m​m​e​t​r​i​c​ ​f​i​e​l​d
				 */
				createSymmetricField: string
				/**
				 * L​i​m​i​t​ ​r​e​c​o​r​d​ ​s​e​l​e​c​t​i​o​n​ ​t​o​ ​c​o​n​d​i​t​i​o​n​.
				 */
				limitRecordSelectionToCondition: string
				/**
				 * M​i​n​ ​i​t​e​m​s
				 */
				min: string
				/**
				 * M​a​x​ ​i​t​e​m​s
				 */
				max: string
				/**
				 * M​i​n​ ​i​t​e​m​s​.​.​.
				 */
				minPlaceholder: string
				/**
				 * M​a​x​ ​i​t​e​m​s​.​.​.
				 */
				maxPlaceholder: string
			}
			rollup: {
				/**
				 * R​e​f​e​r​e​n​c​e​ ​f​i​e​l​d
				 */
				referenceField: string
				/**
				 * S​e​l​e​c​t​ ​r​e​f​e​r​e​n​c​e​ ​f​i​e​l​d​.​.​.
				 */
				selectReferenceField: string
				/**
				 * F​o​r​e​i​g​n​ ​r​o​l​l​u​p​ ​f​i​e​l​d
				 */
				foreignRollupField: string
				/**
				 * A​g​g​r​e​g​a​t​e​ ​f​u​n​c​t​i​o​n
				 */
				aggregateFunction: string
			}
			button: {
				/**
				 * L​a​b​e​l
				 */
				label: string
				/**
				 * D​i​s​a​b​l​e​d​ ​w​h​e​n​.​.​.
				 */
				disabledWhen: string
				/**
				 * U​p​d​a​t​e​ ​v​a​l​u​e​ ​w​h​e​n​ ​c​l​i​c​k​ ​b​u​t​t​o​n
				 */
				updateValueWhenClickButton: string
				/**
				 * C​o​n​f​i​r​m​ ​b​e​f​o​r​e​ ​u​p​d​a​t​e
				 */
				confirmBeforeUpdate: string
				/**
				 * A​d​d​ ​a​n​o​t​h​e​r​ ​f​i​e​l​d​ ​t​o​ ​u​p​d​a​t​e
				 */
				addAnotherFieldToUpdate: string
				/**
				 * V​a​l​u​e​ ​t​o​ ​u​p​d​a​t​e​.​.​.
				 */
				valueToUpdate: string
			}
		}
		view: {
			field: {
				/**
				 * S​h​o​w​ ​a​l​l​ ​f​i​e​l​d​s
				 */
				showAllFields: string
				/**
				 * H​i​d​e​ ​a​l​l​ ​f​i​e​l​d​s
				 */
				hideAllFields: string
				/**
				 * S​h​o​w​ ​s​y​s​t​e​m​ ​f​i​e​l​d​s
				 */
				showSystemFields: string
				/**
				 * H​i​d​e​ ​s​y​s​t​e​m​ ​f​i​e​l​d​s
				 */
				hideSystemFields: string
			}
			widget: {
				/**
				 * V​i​e​w​ ​W​i​d​g​e​t​s
				 */
				title: string
				/**
				 * N​o​ ​w​i​d​g​e​t​s
				 */
				empty: string
				/**
				 * A​d​d​ ​W​i​d​g​e​t
				 */
				add: string
			}
			kanban: {
				/**
				 * K​a​n​b​a​n
				 */
				kanban: string
				/**
				 * U​p​d​a​t​e​ ​K​a​n​b​a​n​ ​V​i​e​w
				 */
				update: string
				/**
				 * K​a​n​b​a​n​ ​V​i​e​w
				 */
				view: string
				/**
				 * K​a​n​b​a​n​ ​F​i​e​l​d
				 */
				field: string
				/**
				 * G​r​o​u​p​ ​b​y​ ​s​e​l​e​c​t​ ​t​y​p​e​ ​f​i​e​l​d
				 */
				groupBy: string
				/**
				 * N​o​ ​s​e​l​e​c​t​ ​f​i​e​l​d​ ​f​o​u​n​d​.
				 */
				noSelectField: string
				/**
				 * N​o​ ​o​p​t​i​o​n
				 */
				noOption: string
				/**
				 * C​o​l​l​a​p​s​e​ ​l​a​n​e
				 */
				collapseLane: string
			}
			gallery: {
				/**
				 * G​a​l​l​e​r​y
				 */
				gallery: string
				/**
				 * U​p​d​a​t​e​ ​G​a​l​l​e​r​y​ ​V​i​e​w
				 */
				update: string
				/**
				 * G​a​l​l​e​r​y​ ​V​i​e​w
				 */
				view: string
				/**
				 * G​a​l​l​e​r​y​ ​F​i​e​l​d
				 */
				field: string
				/**
				 * G​r​o​u​p​ ​b​y​ ​a​t​t​a​c​h​m​e​n​t​ ​t​y​p​e​ ​f​i​e​l​d
				 */
				groupBy: string
				/**
				 * N​o​ ​a​t​t​a​c​h​m​e​n​t​ ​t​y​p​e​ ​f​i​e​l​d​ ​f​o​u​n​d​.
				 */
				noAttachmentField: string
			}
			calendar: {
				/**
				 * C​a​l​e​n​d​a​r
				 */
				calendar: string
				/**
				 * U​p​d​a​t​e​ ​C​a​l​e​n​d​a​r​ ​V​i​e​w
				 */
				update: string
				/**
				 * C​a​l​e​n​d​a​r​ ​V​i​e​w
				 */
				view: string
				/**
				 * C​a​l​e​n​d​a​r​ ​F​i​e​l​d
				 */
				field: string
				/**
				 * G​r​o​u​p​ ​b​y​ ​d​a​t​e​ ​f​i​e​l​d
				 */
				groupBy: string
				/**
				 * N​o​ ​d​a​t​e​ ​f​i​e​l​d​ ​f​o​u​n​d​.
				 */
				noDateField: string
				/**
				 * S​e​l​e​c​t​ ​a​ ​s​e​l​e​c​t​ ​t​y​p​e​ ​f​i​e​l​d​ ​t​o​ ​g​r​o​u​p​ ​c​a​l​e​n​d​a​r​ ​l​a​n​e​s
				 */
				select: string
				/**
				 * S​e​l​e​c​t​ ​c​a​l​e​n​d​a​r​ ​f​i​e​l​d
				 */
				selectField: string
				scope: {
					/**
					 * I​n​ ​s​e​l​e​c​t​e​d​ ​d​a​t​e
					 */
					selectedDate: string
					/**
					 * W​i​t​h​o​u​t​ ​d​a​t​e
					 */
					withoutDate: string
					/**
					 * I​n​ ​t​h​i​s​ ​m​o​n​t​h
					 */
					thisMonth: string
					/**
					 * A​l​l​ ​r​e​c​o​r​d​s
					 */
					allRecords: string
					/**
					 * I​n​ ​t​h​i​s​ ​w​e​e​k
					 */
					thisWeek: string
				}
			}
			pivot: {
				/**
				 * P​i​v​o​t
				 */
				pivot: string
				/**
				 * U​p​d​a​t​e​ ​P​i​v​o​t​ ​V​i​e​w
				 */
				update: string
				/**
				 * P​i​v​o​t​ ​V​i​e​w
				 */
				view: string
				/**
				 * C​o​l​u​m​n​ ​L​a​b​e​l
				 */
				columnLabel: string
				/**
				 * R​o​w​ ​L​a​b​e​l
				 */
				rowLabel: string
				/**
				 * S​w​a​p​ ​w​i​t​h​ ​C​o​l​u​m​n​ ​L​a​b​e​l
				 */
				swap: string
				/**
				 * A​g​g​r​e​g​a​t​e
				 */
				aggregate: string
				aggregateFn: {
					/**
					 * S​u​m
					 */
					sum: string
					/**
					 * C​o​u​n​t
					 */
					count: string
					/**
					 * A​v​e​r​a​g​e
					 */
					average: string
					/**
					 * M​a​x
					 */
					max: string
					/**
					 * M​i​n
					 */
					min: string
				}
				/**
				 * V​a​l​u​e
				 */
				value: string
				/**
				 * S​e​l​e​c​t​ ​a​ ​f​i​e​l​d​ ​t​o​ ​p​i​v​o​t​.​.​.
				 */
				selectField: string
			}
			/**
			 * C​r​e​a​t​e​ ​V​i​e​w
			 */
			create: string
			/**
			 * V​i​e​w​ ​c​r​e​a​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y
			 */
			created: string
			/**
			 * V​i​e​w​ ​T​y​p​e
			 */
			type: string
			/**
			 * V​i​e​w​ ​u​p​d​a​t​e​d
			 */
			updated: string
			/**
			 * U​p​d​a​t​e​ ​V​i​e​w​ ​N​a​m​e
			 */
			updateName: string
			/**
			 * D​u​p​l​i​c​a​t​e​ ​V​i​e​w
			 */
			duplicateView: string
			/**
			 * D​e​l​e​t​e​ ​V​i​e​w
			 */
			deleteView: string
			/**
			 * D​o​w​n​l​o​a​d​ ​V​i​e​w
			 */
			downloadView: string
			/**
			 * D​o​w​n​l​o​a​d​ ​a​s​ ​E​x​c​e​l
			 */
			downloadAsExcel: string
			/**
			 * D​o​w​n​l​o​a​d​ ​a​s​ ​C​S​V
			 */
			downloadAsCSV: string
			/**
			 * D​o​w​n​l​o​a​d​ ​a​s​ ​J​S​O​N
			 */
			downloadAsJSON: string
			/**
			 * S​e​t​ ​a​s​ ​D​e​f​a​u​l​t​ ​V​i​e​w
			 */
			setAsDefaultView: string
		}
		aggregate: {
			/**
			 * S​e​a​r​c​h​ ​a​g​g​r​e​g​a​t​e​ ​t​y​p​e​.​.​.
			 */
			searchType: string
			/**
			 * S​e​l​e​c​t​ ​A​ ​F​i​e​l​d​ ​t​o​ ​A​g​g​r​e​g​a​t​e​.​.​.
			 */
			selectField: string
		}
		schema: {
			/**
			 * S​c​h​e​m​a
			 */
			label: string
			/**
			 * S​y​s​t​e​m​ ​F​i​e​l​d​s
			 */
			systemFields: string
			/**
			 * R​e​q​u​i​r​e​d
			 */
			required: string
			/**
			 * D​i​s​p​l​a​y
			 */
			display: string
			/**
			 * F​i​e​l​d​ ​N​a​m​e
			 */
			fieldName: string
			/**
			 * A​d​d​ ​F​i​e​l​d
			 */
			addField: string
		}
		events: {
			record: {
				/**
				 * R​e​c​o​r​d​ ​C​r​e​a​t​e​d
				 */
				created: string
				/**
				 * R​e​c​o​r​d​ ​U​p​d​a​t​e​d
				 */
				updated: string
				/**
				 * R​e​c​o​r​d​ ​D​e​l​e​t​e​d
				 */
				deleted: string
			}
		}
		'import': {
			/**
			 * I​m​p​o​r​t​ ​F​i​l​e​.​.​.
			 */
			importFile: string
			/**
			 * F​i​r​s​t​ ​r​o​w​ ​a​s​ ​h​e​a​d​e​r
			 */
			firstRowAsHeader: string
			/**
			 * I​m​p​o​r​t​ ​D​a​t​a
			 */
			importData: string
			/**
			 * {​c​o​u​n​t​}​ ​f​i​e​l​d​s​ ​s​e​l​e​c​t​e​d
			 * @param {unknown} count
			 */
			fieldsSelected: RequiredParams<'count'>
			/**
			 * C​o​n​f​i​g​ ​F​i​e​l​d
			 */
			configField: string
			/**
			 * N​e​x​t​ ​s​t​e​p
			 */
			nextStep: string
		}
	}
	common: {
		/**
		 * B​a​c​k
		 */
		back: string
		/**
		 * E​r​r​o​r
		 */
		error: string
		/**
		 * D​u​p​l​i​c​a​t​e
		 */
		duplicate: string
		/**
		 * D​e​s​c​r​i​p​t​i​o​n
		 */
		description: string
		/**
		 * C​a​n​c​e​l
		 */
		cancel: string
		/**
		 * C​r​e​a​t​e
		 */
		create: string
		/**
		 * S​e​l​e​c​t
		 */
		select: string
		/**
		 * E​v​e​n​t
		 */
		event: string
		/**
		 * C​r​e​a​t​i​n​g
		 */
		creating: string
		/**
		 * S​e​a​r​c​h
		 */
		search: string
		/**
		 * C​o​n​f​i​r​m
		 */
		confirm: string
		/**
		 * U​p​d​a​t​e
		 */
		update: string
		/**
		 * C​o​n​t​i​n​u​e
		 */
		'continue': string
		/**
		 * S​u​b​m​i​t
		 */
		submit: string
		/**
		 * D​e​l​e​t​e
		 */
		'delete': string
		/**
		 * S​e​t​t​i​n​g​s
		 */
		settings: string
		/**
		 * S​a​v​e
		 */
		save: string
		/**
		 * L​a​n​g​u​a​g​e
		 */
		language: string
		/**
		 * D​a​t​a
		 */
		data: string
		/**
		 * A​u​t​h
		 */
		auth: string
		/**
		 * D​e​v​e​l​o​p​e​r
		 */
		developer: string
		/**
		 * N​a​m​e
		 */
		name: string
		/**
		 * D​a​n​g​e​r​ ​Z​o​n​e
		 */
		dangerZone: string
		/**
		 * R​e​m​o​v​e
		 */
		remove: string
		/**
		 * A​c​c​o​u​n​t​ ​a​n​d​ ​S​p​a​c​e​ ​S​e​t​t​i​n​g​s
		 */
		accountAndSpaceSettings: string
		/**
		 * E​m​a​i​l
		 */
		email: string
		/**
		 * R​o​l​e
		 */
		role: string
		/**
		 * A​c​t​i​o​n
		 */
		action: string
		/**
		 * S​t​a​t​u​s
		 */
		status: string
		/**
		 * R​e​q​u​i​r​e​d
		 */
		required: string
		/**
		 * E​n​a​b​l​e​d
		 */
		enabled: string
		/**
		 * E​n​a​b​l​e​ ​C​o​n​d​i​t​i​o​n
		 */
		enableCondition: string
		/**
		 * T​y​p​e
		 */
		type: string
		/**
		 * L​o​a​d​ ​m​o​r​e
		 */
		loadMore: string
		/**
		 * T​o​d​a​y
		 */
		today: string
		/**
		 * C​l​e​a​r
		 */
		clear: string
		/**
		 * U​p​d​a​t​e​d
		 */
		updated: string
		/**
		 * N​o​w
		 */
		now: string
		/**
		 * I​m​p​o​r​t
		 */
		'import': string
	}
	share: {
		/**
		 * S​h​a​r​e
		 */
		title: string
		/**
		 * S​h​a​r​e​ ​U​R​L
		 */
		shareUrl: string
		/**
		 * I​F​r​a​m​e​ ​U​R​L
		 */
		iframeUrl: string
		/**
		 * S​h​a​r​e​ ​I​D
		 */
		shareId: string
		/**
		 * E​n​a​b​l​e​ ​s​h​a​r​i​n​g
		 */
		enable: string
		/**
		 * C​o​p​i​e​d​ ​t​o​ ​c​l​i​p​b​o​a​r​d
		 */
		copied: string
		/**
		 * S​h​a​r​e
		 */
		button: string
	}
	widget: {
		/**
		 * W​i​d​g​e​t
		 */
		title: string
		/**
		 * W​i​d​g​e​t​s
		 */
		button: string
		/**
		 * N​a​m​e
		 */
		name: string
		/**
		 * A​d​d​ ​W​i​d​g​e​t
		 */
		add: string
		/**
		 * T​y​p​e
		 */
		type: string
		/**
		 * E​d​i​t​ ​N​a​m​e
		 */
		editName: string
		/**
		 * D​u​p​l​i​c​a​t​e​ ​W​i​d​g​e​t​ ​{​n​a​m​e​}
		 * @param {unknown} name
		 */
		duplicate: RequiredParams<'name'>
		/**
		 * D​e​l​e​t​e​ ​W​i​d​g​e​t​ ​{​n​a​m​e​}
		 * @param {unknown} name
		 */
		'delete': RequiredParams<'name'>
		deleteConfirm: {
			/**
			 * D​e​l​e​t​e​ ​W​i​d​g​e​t​ ​{​n​a​m​e​}​?
			 * @param {unknown} name
			 */
			title: RequiredParams<'name'>
			/**
			 * T​h​i​s​ ​a​c​t​i​o​n​ ​c​a​n​n​o​t​ ​b​e​ ​u​n​d​o​n​e​.​ ​T​h​i​s​ ​w​i​l​l​ ​p​e​r​m​a​n​e​n​t​l​y​ ​d​e​l​e​t​e​ ​t​h​i​s​ ​w​i​d​g​e​t​.​ ​a​n​d​ ​r​e​m​o​v​e​ ​y​o​u​r​ ​d​a​t​a​ ​f​r​o​m​ ​o​u​r​ ​s​e​r​v​e​r​s​.
			 */
			description: string
		}
		/**
		 * C​o​u​n​t
		 */
		count: string
		/**
		 * A​g​g​r​e​g​a​t​e
		 */
		aggregate: string
		/**
		 * F​i​l​t​e​r​s
		 */
		filters: string
	}
	dashboard: {
		/**
		 * D​a​s​h​b​o​a​r​d​s
		 */
		dashboards: string
		/**
		 * C​r​e​a​t​e​ ​D​a​s​h​b​o​a​r​d
		 */
		create: string
		/**
		 * D​a​s​h​b​o​a​r​d​'​s​ ​p​u​b​l​i​c​ ​d​i​s​p​l​a​y​ ​n​a​m​e​.
		 */
		nameDescription: string
		/**
		 * U​p​d​a​t​e​ ​D​a​s​h​b​o​a​r​d​ ​N​a​m​e
		 */
		updateName: string
		/**
		 * D​u​p​l​i​c​a​t​e​ ​D​a​s​h​b​o​a​r​d
		 */
		duplicateDashboard: string
		/**
		 * D​e​l​e​t​e​ ​D​a​s​h​b​o​a​r​d
		 */
		deleteDashboard: string
		/**
		 * C​o​n​f​i​r​m​ ​t​o​ ​d​e​l​e​t​e​ ​d​a​s​h​b​o​a​r​d​?
		 */
		confirmDeleteDashboard: string
		/**
		 * T​h​i​s​ ​a​c​t​i​o​n​ ​c​a​n​n​o​t​ ​b​e​ ​u​n​d​o​n​e​.​ ​T​h​i​s​ ​w​i​l​l​ ​p​e​r​m​a​n​e​n​t​l​y​ ​d​e​l​e​t​e​ ​y​o​u​r​ ​d​a​s​h​b​o​a​r​d​ ​a​n​d​ ​r​e​m​o​v​e​ ​y​o​u​r​ ​d​a​t​a​ ​f​r​o​m​ ​o​u​r​ ​s​e​r​v​e​r​s​.
		 */
		confirmDeleteDashboardDescription: string
		/**
		 * C​o​n​f​i​r​m​ ​t​o​ ​d​u​p​l​i​c​a​t​e​ ​d​a​s​h​b​o​a​r​d​?
		 */
		duplicateDashboardDescription: string
		/**
		 * D​u​p​l​i​c​a​t​e​ ​D​a​s​h​b​o​a​r​d
		 */
		duplicateDashboardConfirm: string
		/**
		 * U​p​d​a​t​e​ ​D​a​s​h​b​o​a​r​d
		 */
		updateDashboard: string
	}
}

export type TranslationFunctions = {
	playground: {
		/**
		 * Playground Mode
		 */
		playgroundMode: () => LocalizedString
		/**
		 * You are in playground mode, all changes will be lost after you close or refresh the page.
		 */
		playgroundModeDescription: () => LocalizedString
	}
	auth: {
		/**
		 * Login
		 */
		login: () => LocalizedString
		/**
		 * Login failed
		 */
		loginFailed: () => LocalizedString
		/**
		 * Go to space
		 */
		gotoSpace: () => LocalizedString
		/**
		 * Forgot your password?
		 */
		forgotPassword: () => LocalizedString
		/**
		 * Enter your email to login
		 */
		emailPlaceholder: () => LocalizedString
		/**
		 * Password
		 */
		password: () => LocalizedString
		/**
		 * Register
		 */
		register: () => LocalizedString
		/**
		 * Don't have an account?
		 */
		noAccount: () => LocalizedString
		/**
		 * Registration is disabled.
		 */
		registerDisabled: () => LocalizedString
		/**
		 * Contact your administrator to request access.
		 */
		registerDisabledDescription: () => LocalizedString
		/**
		 * Login with {provider}
		 */
		loginWith: (arg: { provider: unknown }) => LocalizedString
		/**
		 * Invalid email or password.
		 */
		invalidEmailOrPassword: () => LocalizedString
		/**
		 * Login to your account and accept the invitation
		 */
		loginToYourAccountAndAcceptTheInvitation: () => LocalizedString
		/**
		 * Enter your email and password to login.
		 */
		loginWithEmailDescription: () => LocalizedString
		/**
		 * Enter your email below to reset your password.
		 */
		enterYourEmailBelowToResetYourPassword: () => LocalizedString
		/**
		 * Email sent!
		 */
		emailSent: () => LocalizedString
		/**
		 * You can check your email address and follow the steps to reset your password.
		 */
		youCanCheckYourEmailAddressAndFollowTheStepsToResetYourPassword: () => LocalizedString
		/**
		 * Register failed
		 */
		registerFailed: () => LocalizedString
		/**
		 * Password does not match
		 */
		passwordDoesNotMatch: () => LocalizedString
		/**
		 * Enter your display username
		 */
		enterYourDisplayUsername: () => LocalizedString
		/**
		 * Username
		 */
		username: () => LocalizedString
		/**
		 * Invited
		 */
		invited: () => LocalizedString
		/**
		 * Confirm password
		 */
		confirmPassword: () => LocalizedString
		/**
		 * Create an account
		 */
		createAnAccount: () => LocalizedString
		/**
		 * Already have an account?
		 */
		alreadyHaveAnAccount: () => LocalizedString
		/**
		 * Sign in
		 */
		signIn: () => LocalizedString
		/**
		 * Create account and accept invitation
		 */
		createAccountAndAcceptInvitation: () => LocalizedString
		/**
		 * Enter your information to create an account.
		 */
		enterYourInformationToCreateAnAccount: () => LocalizedString
		/**
		 * Enter your work email...
		 */
		enterYourWorkEmail: () => LocalizedString
		/**
		 * Send Code
		 */
		sendOtpCode: () => LocalizedString
		/**
		 * Verify Code
		 */
		verifyOtp: () => LocalizedString
	}
	template: {
		/**
		 * Template
		 */
		template: () => LocalizedString
		/**
		 * Use this template
		 */
		useThisTemplate: () => LocalizedString
		/**
		 * Preview Template
		 */
		previewTemplate: () => LocalizedString
		/**
		 * Get Started with this template
		 */
		getStarted: () => LocalizedString
		/**
		 * Which space do you want to create this template in?
		 */
		whichSpace: () => LocalizedString
		/**
		 * You can create a new base or a new table in the selected space.
		 */
		whichSpaceDescription: () => LocalizedString
		/**
		 * Create New Base
		 */
		createBase: () => LocalizedString
		/**
		 * Select a template to create a new base
		 */
		selectATemplateToCreateABase: () => LocalizedString
		/**
		 * Include data from the template to the new base or table.
		 */
		includeDataDescription: () => LocalizedString
		/**
		 * Login to create a new base or table
		 */
		loginToCreateNewBaseOrTable: () => LocalizedString
	}
	setting: {
		/**
		 * Settings
		 */
		setting: () => LocalizedString
		/**
		 * Members
		 */
		members: () => LocalizedString
		/**
		 * Settings & Members
		 */
		settingAndMembers: () => LocalizedString
	}
	base: {
		/**
		 * Base Name
		 */
		name: () => LocalizedString
		/**
		 * Create New Base
		 */
		createBase: () => LocalizedString
		/**
		 * Base created successfully
		 */
		created: () => LocalizedString
		/**
		 * Import From Template
		 */
		importFromTemplate: () => LocalizedString
		/**
		 * Base Display Name
		 */
		displayName: () => LocalizedString
		/**
		 * No Bases
		 */
		noBases: () => LocalizedString
		/**
		 * Base Settings
		 */
		baseSettings: () => LocalizedString
		/**
		 * Update Base
		 */
		updateBase: () => LocalizedString
		/**
		 * Update Base Name
		 */
		updateBaseName: () => LocalizedString
		/**
		 * Delete Base
		 */
		deleteBase: () => LocalizedString
		/**
		 * Are you sure you want to delete the following base?
		 */
		deleteBaseConfirm: () => LocalizedString
		/**
		 * Duplicate Base {name}
		 */
		duplicateBase: (arg: { name: unknown }) => LocalizedString
		/**
		 * Base's display name.
		 */
		nameDescription: () => LocalizedString
		/**
		 * Include Data
		 */
		includeData: () => LocalizedString
		/**
		 * Include data in the new base.
		 */
		includeDataDescription: () => LocalizedString
		/**
		 * Create a new base include all tables in base.
		 */
		duplicateBaseDescription: () => LocalizedString
		/**
		 * System fields will be updated to the current user and timestamp.
		 */
		systemFieldsUpdated: () => LocalizedString
	}
	space: {
		/**
		 * Space
		 */
		space: () => LocalizedString
		/**
		 * Spaces
		 */
		spaces: () => LocalizedString
		/**
		 * Space Name
		 */
		name: () => LocalizedString
		/**
		 * Set Display Name
		 */
		setDisplayName: () => LocalizedString
		/**
		 * Search members...
		 */
		searchMembers: () => LocalizedString
		/**
		 * You cannot invite member to a personal space.
		 */
		cannotInviteMemberToPersonalSpace: () => LocalizedString
		/**
		 * Create Space
		 */
		createSpace: () => LocalizedString
		/**
		 * {username}'s Personal Space
		 */
		personalSpace: (arg: { username: unknown }) => LocalizedString
		/**
		 * Create new space to organize your data and collaborate with your team.
		 */
		createSpaceDescription: () => LocalizedString
		/**
		 * Space Name
		 */
		spaceName: () => LocalizedString
		/**
		 * Space's display name.
		 */
		spaceNameDescription: () => LocalizedString
		/**
		 * You can not delete your personal space.
		 */
		cannotDeletePersonalSpace: () => LocalizedString
		/**
		 * Delete Space
		 */
		deleteSpace: () => LocalizedString
		/**
		 * Are you sure you want to delete the following space?
		 */
		deleteSpaceConfirm: () => LocalizedString
		/**
		 * This action cannot be undone. This will permanently delete your database state and remove your data from our servers.
		 */
		deleteSpaceDescription: () => LocalizedString
		/**
		 * A list of your workspace members.
		 */
		memberList: () => LocalizedString
		/**
		 * Invite Member
		 */
		inviteMember: () => LocalizedString
		/**
		 * Invitations
		 */
		invitations: () => LocalizedString
		/**
		 * Invite
		 */
		invite: () => LocalizedString
		/**
		 * A list of pending invitations.
		 */
		pendingInvitations: () => LocalizedString
		/**
		 * Invited At
		 */
		invitedAt: () => LocalizedString
		/**
		 * Delete Invitation
		 */
		deleteInvitation: () => LocalizedString
	}
	account: {
		/**
		 * Log Out
		 */
		logout: () => LocalizedString
		/**
		 * Account Settings
		 */
		accountSettings: () => LocalizedString
		/**
		 * Api Token
		 */
		apiToken: () => LocalizedString
		/**
		 * Undb Templates
		 */
		undbTemplates: () => LocalizedString
		/**
		 * Undb Website
		 */
		undbWebsite: () => LocalizedString
	}
	roles: {
		/**
		 * Owner
		 */
		owner: () => LocalizedString
		/**
		 * Admin
		 */
		admin: () => LocalizedString
		/**
		 * Member
		 */
		member: () => LocalizedString
		/**
		 * Viewer
		 */
		viewer: () => LocalizedString
	}
	webhook: {
		/**
		 * Webhook
		 */
		label: () => LocalizedString
		/**
		 * Create Webhook
		 */
		create: () => LocalizedString
		/**
		 * Delete Webhook
		 */
		'delete': () => LocalizedString
		/**
		 * Update Webhook
		 */
		update: () => LocalizedString
		/**
		 * Duplicate Webhook
		 */
		duplicate: () => LocalizedString
		/**
		 * {table} have no webhooks
		 */
		noWebhooks: (arg: { table: unknown }) => LocalizedString
		/**
		 * Click button to create your first webhook
		 */
		noWebhooksDescription: () => LocalizedString
	}
	table: {
		authz: {
			/**
			 * {table} have no record level security
			 */
			noRecordLevelSecurity: (arg: { table: unknown }) => LocalizedString
			/**
			 * Click button to create your first record level security policy
			 */
			noRecordLevelSecurityDescription: () => LocalizedString
			/**
			 * Create Record Level Security
			 */
			create: () => LocalizedString
			/**
			 * Record level security created
			 */
			created: () => LocalizedString
			/**
			 * Failed to create record level security
			 */
			failed: () => LocalizedString
			/**
			 * Record Level Security Name
			 */
			rlsName: () => LocalizedString
			/**
			 * Give your record level security a name
			 */
			giveYourRLSName: () => LocalizedString
			actions: {
				/**
				 * Read
				 */
				read: () => LocalizedString
				/**
				 * Create
				 */
				create: () => LocalizedString
				/**
				 * Update
				 */
				update: () => LocalizedString
				/**
				 * Delete
				 */
				'delete': () => LocalizedString
			}
			/**
			 * Subject
			 */
			subjectName: () => LocalizedString
			subject: {
				/**
				 * Any user
				 */
				any: () => LocalizedString
				/**
				 * Specific user
				 */
				user: () => LocalizedString
				/**
				 * Specific user group
				 */
				group: () => LocalizedString
			}
			/**
			 * Action
			 */
			action: () => LocalizedString
			/**
			 * Allow
			 */
			allow: () => LocalizedString
			/**
			 * Deny
			 */
			deny: () => LocalizedString
			/**
			 * Matches conditions...
			 */
			matchesConditions: () => LocalizedString
			/**
			 * Update condition
			 */
			updateCondition: () => LocalizedString
			/**
			 * Not allow to
			 */
			notAllow: () => LocalizedString
			policy: {
				/**
				 * Update policy
				 */
				update: () => LocalizedString
				/**
				 * Delete policy
				 */
				'delete': () => LocalizedString
			}
			/**
			 * Update Record Level Security
			 */
			updateRLS: () => LocalizedString
		}
		ops: {
			/**
			 * =
			 */
			eq: () => LocalizedString
			/**
			 * !=
			 */
			neq: () => LocalizedString
			/**
			 * Contains
			 */
			contains: () => LocalizedString
			/**
			 * Not Contains
			 */
			does_not_contain: () => LocalizedString
			/**
			 * Starts With
			 */
			starts_with: () => LocalizedString
			/**
			 * Ends With
			 */
			ends_with: () => LocalizedString
			/**
			 * Is Empty
			 */
			is_empty: () => LocalizedString
			/**
			 * Is Not Empty
			 */
			is_not_empty: () => LocalizedString
			/**
			 * Min
			 */
			min: () => LocalizedString
			/**
			 * Max
			 */
			max: () => LocalizedString
			/**
			 * >
			 */
			gt: () => LocalizedString
			/**
			 * >=
			 */
			gte: () => LocalizedString
			/**
			 * <
			 */
			lt: () => LocalizedString
			/**
			 * <=
			 */
			lte: () => LocalizedString
			/**
			 * In
			 */
			'in': () => LocalizedString
			/**
			 * Not In
			 */
			nin: () => LocalizedString
			/**
			 * Any Of
			 */
			any_of: () => LocalizedString
			/**
			 * Not Any Of
			 */
			not_any_of: () => LocalizedString
			/**
			 * Is Same Day
			 */
			is_same_day: () => LocalizedString
			/**
			 * Is Not Same Day
			 */
			is_not_same_day: () => LocalizedString
			/**
			 * Is Today
			 */
			is_tody: () => LocalizedString
			/**
			 * Is Not Today
			 */
			is_not_today: () => LocalizedString
			/**
			 * Is After Today
			 */
			is_after_today: () => LocalizedString
			/**
			 * Is Before Today
			 */
			is_before_today: () => LocalizedString
			/**
			 * Is Tomorrow
			 */
			is_tomorrow: () => LocalizedString
			/**
			 * Is Not Tomorrow
			 */
			is_not_tomorrow: () => LocalizedString
			/**
			 * Is After Tomorrow
			 */
			is_after_tomorrow: () => LocalizedString
			/**
			 * Is Before Tomorrow
			 */
			is_before_tommorow: () => LocalizedString
			/**
			 * Is Yesterday
			 */
			is_yesterday: () => LocalizedString
			/**
			 * Is Not Yesterday
			 */
			is_not_yesterday: () => LocalizedString
			/**
			 * Is After Yesterday
			 */
			is_after_yesterday: () => LocalizedString
			/**
			 * Is Before Yesterday
			 */
			is_before_yesterday: () => LocalizedString
			/**
			 * Is Before
			 */
			is_before: () => LocalizedString
			/**
			 * Is Not Before
			 */
			is_not_before: () => LocalizedString
			/**
			 * Is After
			 */
			is_after: () => LocalizedString
			/**
			 * Is Not After
			 */
			is_not_after: () => LocalizedString
			/**
			 * Is True
			 */
			is_true: () => LocalizedString
			/**
			 * Is False
			 */
			is_false: () => LocalizedString
		}
		fieldTypes: {
			/**
			 * String
			 */
			string: () => LocalizedString
			/**
			 * Long Text
			 */
			longText: () => LocalizedString
			/**
			 * Number
			 */
			number: () => LocalizedString
			/**
			 * Date
			 */
			date: () => LocalizedString
			/**
			 * Date Range
			 */
			dateRange: () => LocalizedString
			/**
			 * ID
			 */
			id: () => LocalizedString
			/**
			 * Created At
			 */
			createdAt: () => LocalizedString
			/**
			 * Auto Increment
			 */
			autoIncrement: () => LocalizedString
			/**
			 * Updated At
			 */
			updatedAt: () => LocalizedString
			/**
			 * Created By
			 */
			createdBy: () => LocalizedString
			/**
			 * Updated By
			 */
			updatedBy: () => LocalizedString
			/**
			 * Reference
			 */
			reference: () => LocalizedString
			/**
			 * Rollup
			 */
			rollup: () => LocalizedString
			/**
			 * Select
			 */
			select: () => LocalizedString
			/**
			 * Rating
			 */
			rating: () => LocalizedString
			/**
			 * Email
			 */
			email: () => LocalizedString
			/**
			 * URL
			 */
			url: () => LocalizedString
			/**
			 * Attachment
			 */
			attachment: () => LocalizedString
			/**
			 * JSON
			 */
			json: () => LocalizedString
			/**
			 * Checkbox
			 */
			checkbox: () => LocalizedString
			/**
			 * User
			 */
			user: () => LocalizedString
			/**
			 * Currency
			 */
			currency: () => LocalizedString
			/**
			 * Duration
			 */
			duration: () => LocalizedString
			/**
			 * Button
			 */
			button: () => LocalizedString
			/**
			 * Percentage
			 */
			percentage: () => LocalizedString
			/**
			 * Formula
			 */
			formula: () => LocalizedString
		}
		rollupFns: {
			/**
			 * Min
			 */
			min: () => LocalizedString
			/**
			 * Max
			 */
			max: () => LocalizedString
			/**
			 * Sum
			 */
			sum: () => LocalizedString
			/**
			 * Average
			 */
			average: () => LocalizedString
			/**
			 * Count
			 */
			count: () => LocalizedString
			/**
			 * Lookup
			 */
			lookup: () => LocalizedString
		}
		aggregateFns: {
			/**
			 * Min
			 */
			min: () => LocalizedString
			/**
			 * Max
			 */
			max: () => LocalizedString
			/**
			 * Sum
			 */
			sum: () => LocalizedString
			/**
			 * Count
			 */
			count: () => LocalizedString
			/**
			 * Empty
			 */
			count_empty: () => LocalizedString
			/**
			 * Unique
			 */
			count_uniq: () => LocalizedString
			/**
			 * Filled
			 */
			count_not_empty: () => LocalizedString
			/**
			 * Percent Empty
			 */
			percent_empty: () => LocalizedString
			/**
			 * Percent Filled
			 */
			percent_not_empty: () => LocalizedString
			/**
			 * Percent Unique
			 */
			percent_uniq: () => LocalizedString
			/**
			 * Average
			 */
			avg: () => LocalizedString
			/**
			 * True
			 */
			count_true: () => LocalizedString
			/**
			 * False
			 */
			count_false: () => LocalizedString
			/**
			 * Percent True
			 */
			percent_true: () => LocalizedString
			/**
			 * Percent False
			 */
			percent_false: () => LocalizedString
			/**
			 * Start Date Max
			 */
			start_max: () => LocalizedString
			/**
			 * End Date Max
			 */
			end_max: () => LocalizedString
			/**
			 * Start Date Min
			 */
			start_min: () => LocalizedString
			/**
			 * End Date Min
			 */
			end_min: () => LocalizedString
		}
		macros: {
			/**
			 * Current User
			 */
			'@me': () => LocalizedString
			/**
			 * Now
			 */
			'@now': () => LocalizedString
			/**
			 * Today
			 */
			'@today': () => LocalizedString
			/**
			 * Yesterday
			 */
			'@yesterday': () => LocalizedString
			/**
			 * Tomorrow
			 */
			'@tomorrow': () => LocalizedString
		}
		viewTypes: {
			/**
			 * Grid
			 */
			grid: () => LocalizedString
			/**
			 * Kanban
			 */
			kanban: () => LocalizedString
			/**
			 * Gallery
			 */
			gallery: () => LocalizedString
			/**
			 * List
			 */
			list: () => LocalizedString
			/**
			 * Calendar
			 */
			calendar: () => LocalizedString
			/**
			 * Pivot
			 */
			pivot: () => LocalizedString
		}
		widgetTypes: {
			/**
			 * Aggregate
			 */
			aggregate: () => LocalizedString
			/**
			 * Chart
			 */
			chart: () => LocalizedString
			/**
			 * Table
			 */
			table: () => LocalizedString
		}
		timeScales: {
			/**
			 * Month
			 */
			month: () => LocalizedString
			/**
			 * Week
			 */
			week: () => LocalizedString
			/**
			 * Day
			 */
			day: () => LocalizedString
		}
		record: {
			/**
			 * Record
			 */
			label: () => LocalizedString
			/**
			 * Records
			 */
			labels: () => LocalizedString
			/**
			 * Search Records...
			 */
			search: () => LocalizedString
			/**
			 * Open Menu
			 */
			openMenu: () => LocalizedString
			/**
			 * Create Record
			 */
			create: () => LocalizedString
			/**
			 * Update Record
			 */
			update: () => LocalizedString
			/**
			 * Delete Record
			 */
			'delete': () => LocalizedString
			/**
			 * View Record Detail
			 */
			viewRecordDetail: () => LocalizedString
			/**
			 * Copy Record ID
			 */
			copyRecordId: () => LocalizedString
			/**
			 * Create By Form
			 */
			createByForm: () => LocalizedString
			/**
			 * Duplicate Record
			 */
			duplicateRecord: () => LocalizedString
			/**
			 * Records have been duplicated!
			 */
			bulkDuplicated: () => LocalizedString
			/**
			 * Include Data
			 */
			includeData: () => LocalizedString
			/**
			 * {n|number} Records
			 */
			records: (arg: { n: unknown }) => LocalizedString
			/**
			 * Record Detail
			 */
			detail: () => LocalizedString
			/**
			 * Duplicate {n|number} Records
			 */
			duplicate: (arg: { n: unknown }) => LocalizedString
			/**
			 * Update {n|number} Records
			 */
			updateRecords: (arg: { n: unknown }) => LocalizedString
			/**
			 * Bulk Update {n|number} Records
			 */
			bulkUpdateRecords: (arg: { n: unknown }) => LocalizedString
			/**
			 * Delete {n|number} Records
			 */
			deleteRecords: (arg: { n: unknown }) => LocalizedString
			/**
			 * Are you sure you want to delete this record?
			 */
			confirmDeleteRecord: () => LocalizedString
			/**
			 * This action cannot be undone. This will permanently delete this record and remove your data from our servers.
			 */
			confirmDeleteRecordDescription: () => LocalizedString
			/**
			 * Are you sure you want to delete {n|number} records?
			 */
			confirmDeleteRecords: (arg: { n: unknown }) => LocalizedString
			/**
			 * This action cannot be undone. This will permanently delete records from {table}.
			 */
			confirmDeleteRecordsDescription: (arg: { table: unknown }) => LocalizedString
			/**
			 * Duplicate {n|number} Records?
			 */
			confirmDuplicateRecords: (arg: { n: unknown }) => LocalizedString
			/**
			 * This action will duplicate {n|number} records of table {table}.
			 */
			confirmDuplicateRecordsDescription: (arg: { n: unknown, table: unknown }) => LocalizedString
			/**
			 * Duplicate Record?
			 */
			confirmDuplicateRecord: () => LocalizedString
			/**
			 * A new record with new id will be created.
			 */
			confirmDuplicateRecordDescription: () => LocalizedString
			/**
			 * Failed to duplicate record
			 */
			failedToDuplicateRecord: () => LocalizedString
			/**
			 * Failed to delete record
			 */
			failedToDeleteRecord: () => LocalizedString
			/**
			 * Copied record ID to clipboard
			 */
			copiedRecordId: () => LocalizedString
			/**
			 * Record has been created!
			 */
			createdRecord: () => LocalizedString
			bulkUpdate: {
				/**
				 * Bulk Update Records
				 */
				title: () => LocalizedString
				/**
				 * All selected fields will be updated
				 */
				description: () => LocalizedString
				/**
				 * Update records with the following condition
				 */
				updateWithCondition: () => LocalizedString
				/**
				 * Add Update Field
				 */
				addField: () => LocalizedString
				/**
				 * SELECT COLUMNS TO EDIT
				 */
				selectColumns: () => LocalizedString
				/**
				 * updated
				 */
				updated: () => LocalizedString
				/**
				 * Select All
				 */
				selectAll: () => LocalizedString
				/**
				 * Remove All
				 */
				removeAll: () => LocalizedString
				/**
				 * Continue
				 */
				'continue': () => LocalizedString
				/**
				 * No records updated
				 */
				noRecordsUpdated: () => LocalizedString
				/**
				 * {count} records updated successfully
				 */
				recordsUpdated: (arg: { count: unknown }) => LocalizedString
				/**
				 * Bulk Update
				 */
				button: () => LocalizedString
				/**
				 * No filter, will update all records, please be careful!
				 */
				noFilterAlert: () => LocalizedString
			}
			reference: {
				/**
				 * Link Records
				 */
				link: () => LocalizedString
				/**
				 * {n|number} Linked Records
				 */
				linked: (arg: { n: unknown }) => LocalizedString
			}
			button: {
				/**
				 * Confirm to update
				 */
				confirmToUpdate: () => LocalizedString
				/**
				 * The following fields will be updated when you click the button.
				 */
				confirmToUpdateDescription: () => LocalizedString
			}
			/**
			 * No record
			 */
			noRecord: () => LocalizedString
			/**
			 * Show {n|number} Hidden Fields
			 */
			showHiddenFields: (arg: { n: unknown }) => LocalizedString
			/**
			 * Hide {n|number} Hidden Fields
			 */
			hideHiddenFields: (arg: { n: unknown }) => LocalizedString
		}
		form: {
			/**
			 * Form
			 */
			label: () => LocalizedString
			/**
			 * Create Form
			 */
			create: () => LocalizedString
			/**
			 * {tableName} have no forms
			 */
			noForms: (arg: { tableName: unknown }) => LocalizedString
			/**
			 * You can collect data in forms.
			 */
			noFormsDescription: () => LocalizedString
			/**
			 * Add description
			 */
			addDescription: () => LocalizedString
			/**
			 * Condition
			 */
			condition: () => LocalizedString
			/**
			 * Invalid condition
			 */
			invalidCondition: () => LocalizedString
			/**
			 * Set default value for {field}
			 */
			setDefaultValue: (arg: { field: unknown }) => LocalizedString
			/**
			 * Form Field
			 */
			formField: () => LocalizedString
			/**
			 * {n} Fields Selected
			 */
			fieldsSelected: (arg: { n: unknown }) => LocalizedString
			/**
			 * Search form field...
			 */
			searchFormField: () => LocalizedString
			/**
			 * Select all fields
			 */
			selectAllFields: () => LocalizedString
			/**
			 * Hide Fields
			 */
			hideFields: () => LocalizedString
			/**
			 * Show Fields
			 */
			showFields: () => LocalizedString
			/**
			 * No fields found with title `{q}`
			 */
			noFieldsFound: (arg: { q: unknown }) => LocalizedString
			/**
			 * Form Setting
			 */
			formSetting: () => LocalizedString
			/**
			 * Duplicate Form
			 */
			duplicateForm: () => LocalizedString
			/**
			 * Delete Form
			 */
			deleteForm: () => LocalizedString
			/**
			 * Duplicate form successfully
			 */
			duplicateSuccess: () => LocalizedString
			/**
			 * Background Color
			 */
			backgroundColor: () => LocalizedString
			/**
			 * Auto add new field to form when create field
			 */
			autoAddNewField: () => LocalizedString
			/**
			 * When a new field is created, it will be automatically set to show.
			 */
			autoAddNewFieldDescription: () => LocalizedString
			/**
			 * Delete form: {name}?
			 */
			deleteFormConfirm: (arg: { name: unknown }) => LocalizedString
			/**
			 * Form will be deleted permanently.
			 */
			deleteFormDescription: () => LocalizedString
			/**
			 * Duplicate form: {name}?
			 */
			duplicateFormDialog: (arg: { name: unknown }) => LocalizedString
			/**
			 * Form will be duplicated.
			 */
			duplicateFormDialogDescription: () => LocalizedString
			/**
			 * Set form name
			 */
			setName: () => LocalizedString
			/**
			 * Enable condition
			 */
			enableCondition: () => LocalizedString
		}
		common: {
			/**
			 * Tables
			 */
			tables: () => LocalizedString
			/**
			 * Table
			 */
			table: () => LocalizedString
			/**
			 * Filter
			 */
			filters: () => LocalizedString
			/**
			 * Color
			 */
			color: () => LocalizedString
			/**
			 * Select A Table...
			 */
			select: () => LocalizedString
			/**
			 * Search Tables...
			 */
			search: () => LocalizedString
			/**
			 * No tables found.
			 */
			noTablesFound: () => LocalizedString
			sorts: {
				/**
				 * Sort
				 */
				sort: () => LocalizedString
				/**
				 * Add Sort
				 */
				add: () => LocalizedString
				/**
				 * There's no sort
				 */
				empty: () => LocalizedString
				direction: {
					/**
					 * Asc
					 */
					asc: () => LocalizedString
					/**
					 * Desc
					 */
					desc: () => LocalizedString
				}
			}
			/**
			 * Fields
			 */
			fields: () => LocalizedString
			filter: {
				/**
				 * There's no filters
				 */
				empty: () => LocalizedString
			}
			condition: {
				/**
				 * Add Condition
				 */
				add: () => LocalizedString
				/**
				 * Add Condition Group
				 */
				addGroup: () => LocalizedString
			}
			/**
			 * Submit
			 */
			submit: () => LocalizedString
			/**
			 * Cancel
			 */
			cancel: () => LocalizedString
			/**
			 * Where
			 */
			where: () => LocalizedString
			/**
			 * Search Op...
			 */
			searchOp: () => LocalizedString
			/**
			 * There's no color
			 */
			colorEmpty: () => LocalizedString
			/**
			 * Update Table Name
			 */
			updateName: () => LocalizedString
			/**
			 * Duplicate Table
			 */
			duplicateTable: () => LocalizedString
			/**
			 * Delete Table
			 */
			deleteTable: () => LocalizedString
			/**
			 * Create New Table
			 */
			create: () => LocalizedString
			/**
			 * Import Table
			 */
			'import': () => LocalizedString
		}
		field: {
			/**
			 * You have changed the field type, data will be cast to new type when possible, but may be cleared
			 */
			typeChanged: () => LocalizedString
			/**
			 * Field
			 */
			field: () => LocalizedString
			/**
			 * Fields
			 */
			fields: () => LocalizedString
			/**
			 * Create Field
			 */
			create: () => LocalizedString
			/**
			 * Field has been created!
			 */
			created: () => LocalizedString
			/**
			 * Update Field
			 */
			update: () => LocalizedString
			/**
			 * Field has been updated!
			 */
			updated: () => LocalizedString
			/**
			 * Delete Field
			 */
			'delete': () => LocalizedString
			/**
			 * Are you sure you want to delete the following field? All data associated with this field will be delete perminently from table.
			 */
			deleteConfirm: () => LocalizedString
			/**
			 * Field has been deleted!
			 */
			deleted: () => LocalizedString
			/**
			 * Failed to delete field
			 */
			deleteFailed: () => LocalizedString
			/**
			 * Duplicate Field
			 */
			duplicate: () => LocalizedString
			/**
			 * Are you sure to duplicate the following field?
			 */
			duplicateDescription: () => LocalizedString
			/**
			 * {n|number} Fields Hidden
			 */
			hidden: (arg: { n: unknown }) => LocalizedString
			/**
			 * Search {table} fields...
			 */
			searchTableFields: (arg: { table: unknown }) => LocalizedString
			/**
			 * Select field...
			 */
			selectField: () => LocalizedString
			/**
			 * No fields
			 */
			empty: () => LocalizedString
			/**
			 * Search field type...
			 */
			searchType: () => LocalizedString
			defaultValue: {
				/**
				 * Default Value
				 */
				label: () => LocalizedString
				/**
				 * Default value...
				 */
				placeholder: () => LocalizedString
				/**
				 * Invalid default value
				 */
				invalid: () => LocalizedString
				/**
				 * Your default value is invalid. Default value will not be saved.
				 */
				invalidDescription: () => LocalizedString
				/**
				 * Mark as required field.
				 */
				markAsRequired: () => LocalizedString
			}
			display: {
				/**
				 * Display FIeld
				 */
				label: () => LocalizedString
				/**
				 * Mark as display field.
				 */
				markAsDisplay: () => LocalizedString
			}
			id: {
				/**
				 * Leave blank to auto generate...
				 */
				placeholder: () => LocalizedString
			}
			string: {
				/**
				 * Min Length
				 */
				min: () => LocalizedString
				/**
				 * Max Length
				 */
				max: () => LocalizedString
			}
			longText: {
				/**
				 * Allow rich text.
				 */
				allowRichText: () => LocalizedString
			}
			number: {
				/**
				 * Min
				 */
				min: () => LocalizedString
				/**
				 * Max
				 */
				max: () => LocalizedString
				/**
				 * Min value...
				 */
				minPlaceholder: () => LocalizedString
				/**
				 * Max value...
				 */
				maxPlaceholder: () => LocalizedString
			}
			duration: {
				/**
				 * Min
				 */
				min: () => LocalizedString
				/**
				 * Max
				 */
				max: () => LocalizedString
				/**
				 * Min value...
				 */
				minPlaceholder: () => LocalizedString
				/**
				 * Max value...
				 */
				maxPlaceholder: () => LocalizedString
			}
			currency: {
				/**
				 * Symbol
				 */
				symbol: () => LocalizedString
				/**
				 * Min
				 */
				min: () => LocalizedString
				/**
				 * Max
				 */
				max: () => LocalizedString
				/**
				 * Min value...
				 */
				minPlaceholder: () => LocalizedString
				/**
				 * Max value...
				 */
				maxPlaceholder: () => LocalizedString
			}
			percentage: {
				/**
				 * Min
				 */
				min: () => LocalizedString
				/**
				 * Max
				 */
				max: () => LocalizedString
				/**
				 * Min value...
				 */
				minPlaceholder: () => LocalizedString
				/**
				 * Max value...
				 */
				maxPlaceholder: () => LocalizedString
			}
			date: {
				/**
				 * Date Format
				 */
				format: () => LocalizedString
				/**
				 * Include Time
				 */
				includeTime: () => LocalizedString
				/**
				 * Time Format
				 */
				timeFormat: () => LocalizedString
				/**
				 * Select Macro...
				 */
				selectMacro: () => LocalizedString
			}
			dateRange: {
				/**
				 * Date Format
				 */
				format: () => LocalizedString
				/**
				 * Include Time
				 */
				includeTime: () => LocalizedString
				/**
				 * Time Format
				 */
				timeFormat: () => LocalizedString
			}
			formula: {
				/**
				 * Formula
				 */
				label: () => LocalizedString
				/**
				 * Formula...
				 */
				placeholder: () => LocalizedString
				/**
				 * Syntax
				 */
				syntax: () => LocalizedString
				/**
				 * Examples
				 */
				examples: () => LocalizedString
			}
			select: {
				option: {
					/**
					 * Option
					 */
					label: () => LocalizedString
					/**
					 * Add Option
					 */
					add: () => LocalizedString
					/**
					 * Select default options...
					 */
					selectDefault: () => LocalizedString
					/**
					 * Search option...
					 */
					search: () => LocalizedString
					/**
					 * No option found.
					 */
					noOptionFound: () => LocalizedString
					/**
					 * Update option
					 */
					update: () => LocalizedString
					/**
					 * Delete option
					 */
					'delete': () => LocalizedString
					/**
					 * Create record under this option
					 */
					createRecord: () => LocalizedString
					/**
					 * Create option
					 */
					create: () => LocalizedString
				}
				/**
				 * Allow add multiple options
				 */
				allowAddMultiple: () => LocalizedString
				/**
				 * Change from multiple options to single option!
				 */
				changeFromMultipleToSingle: () => LocalizedString
				/**
				 * Only first option will be remained.
				 */
				changeFromMultipleToSingleDescription: () => LocalizedString
				/**
				 * Min items
				 */
				min: () => LocalizedString
				/**
				 * Max items
				 */
				max: () => LocalizedString
				/**
				 * Min items...
				 */
				minPlaceholder: () => LocalizedString
				/**
				 * Max items...
				 */
				maxPlaceholder: () => LocalizedString
			}
			attachment: {
				/**
				 * Min items
				 */
				min: () => LocalizedString
				/**
				 * Max items
				 */
				max: () => LocalizedString
				/**
				 * Min items...
				 */
				minPlaceholder: () => LocalizedString
				/**
				 * Max items...
				 */
				maxPlaceholder: () => LocalizedString
			}
			user: {
				/**
				 * Allow adding multiple users
				 */
				allowAddMultiple: () => LocalizedString
				/**
				 * Change from multiple options to single option!
				 */
				changeFromMultipleToSingle: () => LocalizedString
				/**
				 * Only first option will be remained.
				 */
				changeFromMultipleToSingleDescription: () => LocalizedString
				/**
				 * Min items
				 */
				min: () => LocalizedString
				/**
				 * Max items
				 */
				max: () => LocalizedString
				/**
				 * Min items...
				 */
				minPlaceholder: () => LocalizedString
				/**
				 * Max items...
				 */
				maxPlaceholder: () => LocalizedString
			}
			reference: {
				/**
				 * Foreign table
				 */
				foreignTable: () => LocalizedString
				/**
				 * Create symmetric field
				 */
				createSymmetricField: () => LocalizedString
				/**
				 * Limit record selection to condition.
				 */
				limitRecordSelectionToCondition: () => LocalizedString
				/**
				 * Min items
				 */
				min: () => LocalizedString
				/**
				 * Max items
				 */
				max: () => LocalizedString
				/**
				 * Min items...
				 */
				minPlaceholder: () => LocalizedString
				/**
				 * Max items...
				 */
				maxPlaceholder: () => LocalizedString
			}
			rollup: {
				/**
				 * Reference field
				 */
				referenceField: () => LocalizedString
				/**
				 * Select reference field...
				 */
				selectReferenceField: () => LocalizedString
				/**
				 * Foreign rollup field
				 */
				foreignRollupField: () => LocalizedString
				/**
				 * Aggregate function
				 */
				aggregateFunction: () => LocalizedString
			}
			button: {
				/**
				 * Label
				 */
				label: () => LocalizedString
				/**
				 * Disabled when...
				 */
				disabledWhen: () => LocalizedString
				/**
				 * Update value when click button
				 */
				updateValueWhenClickButton: () => LocalizedString
				/**
				 * Confirm before update
				 */
				confirmBeforeUpdate: () => LocalizedString
				/**
				 * Add another field to update
				 */
				addAnotherFieldToUpdate: () => LocalizedString
				/**
				 * Value to update...
				 */
				valueToUpdate: () => LocalizedString
			}
		}
		view: {
			field: {
				/**
				 * Show all fields
				 */
				showAllFields: () => LocalizedString
				/**
				 * Hide all fields
				 */
				hideAllFields: () => LocalizedString
				/**
				 * Show system fields
				 */
				showSystemFields: () => LocalizedString
				/**
				 * Hide system fields
				 */
				hideSystemFields: () => LocalizedString
			}
			widget: {
				/**
				 * View Widgets
				 */
				title: () => LocalizedString
				/**
				 * No widgets
				 */
				empty: () => LocalizedString
				/**
				 * Add Widget
				 */
				add: () => LocalizedString
			}
			kanban: {
				/**
				 * Kanban
				 */
				kanban: () => LocalizedString
				/**
				 * Update Kanban View
				 */
				update: () => LocalizedString
				/**
				 * Kanban View
				 */
				view: () => LocalizedString
				/**
				 * Kanban Field
				 */
				field: () => LocalizedString
				/**
				 * Group by select type field
				 */
				groupBy: () => LocalizedString
				/**
				 * No select field found.
				 */
				noSelectField: () => LocalizedString
				/**
				 * No option
				 */
				noOption: () => LocalizedString
				/**
				 * Collapse lane
				 */
				collapseLane: () => LocalizedString
			}
			gallery: {
				/**
				 * Gallery
				 */
				gallery: () => LocalizedString
				/**
				 * Update Gallery View
				 */
				update: () => LocalizedString
				/**
				 * Gallery View
				 */
				view: () => LocalizedString
				/**
				 * Gallery Field
				 */
				field: () => LocalizedString
				/**
				 * Group by attachment type field
				 */
				groupBy: () => LocalizedString
				/**
				 * No attachment type field found.
				 */
				noAttachmentField: () => LocalizedString
			}
			calendar: {
				/**
				 * Calendar
				 */
				calendar: () => LocalizedString
				/**
				 * Update Calendar View
				 */
				update: () => LocalizedString
				/**
				 * Calendar View
				 */
				view: () => LocalizedString
				/**
				 * Calendar Field
				 */
				field: () => LocalizedString
				/**
				 * Group by date field
				 */
				groupBy: () => LocalizedString
				/**
				 * No date field found.
				 */
				noDateField: () => LocalizedString
				/**
				 * Select a select type field to group calendar lanes
				 */
				select: () => LocalizedString
				/**
				 * Select calendar field
				 */
				selectField: () => LocalizedString
				scope: {
					/**
					 * In selected date
					 */
					selectedDate: () => LocalizedString
					/**
					 * Without date
					 */
					withoutDate: () => LocalizedString
					/**
					 * In this month
					 */
					thisMonth: () => LocalizedString
					/**
					 * All records
					 */
					allRecords: () => LocalizedString
					/**
					 * In this week
					 */
					thisWeek: () => LocalizedString
				}
			}
			pivot: {
				/**
				 * Pivot
				 */
				pivot: () => LocalizedString
				/**
				 * Update Pivot View
				 */
				update: () => LocalizedString
				/**
				 * Pivot View
				 */
				view: () => LocalizedString
				/**
				 * Column Label
				 */
				columnLabel: () => LocalizedString
				/**
				 * Row Label
				 */
				rowLabel: () => LocalizedString
				/**
				 * Swap with Column Label
				 */
				swap: () => LocalizedString
				/**
				 * Aggregate
				 */
				aggregate: () => LocalizedString
				aggregateFn: {
					/**
					 * Sum
					 */
					sum: () => LocalizedString
					/**
					 * Count
					 */
					count: () => LocalizedString
					/**
					 * Average
					 */
					average: () => LocalizedString
					/**
					 * Max
					 */
					max: () => LocalizedString
					/**
					 * Min
					 */
					min: () => LocalizedString
				}
				/**
				 * Value
				 */
				value: () => LocalizedString
				/**
				 * Select a field to pivot...
				 */
				selectField: () => LocalizedString
			}
			/**
			 * Create View
			 */
			create: () => LocalizedString
			/**
			 * View created successfully
			 */
			created: () => LocalizedString
			/**
			 * View Type
			 */
			type: () => LocalizedString
			/**
			 * View updated
			 */
			updated: () => LocalizedString
			/**
			 * Update View Name
			 */
			updateName: () => LocalizedString
			/**
			 * Duplicate View
			 */
			duplicateView: () => LocalizedString
			/**
			 * Delete View
			 */
			deleteView: () => LocalizedString
			/**
			 * Download View
			 */
			downloadView: () => LocalizedString
			/**
			 * Download as Excel
			 */
			downloadAsExcel: () => LocalizedString
			/**
			 * Download as CSV
			 */
			downloadAsCSV: () => LocalizedString
			/**
			 * Download as JSON
			 */
			downloadAsJSON: () => LocalizedString
			/**
			 * Set as Default View
			 */
			setAsDefaultView: () => LocalizedString
		}
		aggregate: {
			/**
			 * Search aggregate type...
			 */
			searchType: () => LocalizedString
			/**
			 * Select A Field to Aggregate...
			 */
			selectField: () => LocalizedString
		}
		schema: {
			/**
			 * Schema
			 */
			label: () => LocalizedString
			/**
			 * System Fields
			 */
			systemFields: () => LocalizedString
			/**
			 * Required
			 */
			required: () => LocalizedString
			/**
			 * Display
			 */
			display: () => LocalizedString
			/**
			 * Field Name
			 */
			fieldName: () => LocalizedString
			/**
			 * Add Field
			 */
			addField: () => LocalizedString
		}
		events: {
			record: {
				/**
				 * Record Created
				 */
				created: () => LocalizedString
				/**
				 * Record Updated
				 */
				updated: () => LocalizedString
				/**
				 * Record Deleted
				 */
				deleted: () => LocalizedString
			}
		}
		'import': {
			/**
			 * Import File...
			 */
			importFile: () => LocalizedString
			/**
			 * First row as header
			 */
			firstRowAsHeader: () => LocalizedString
			/**
			 * Import Data
			 */
			importData: () => LocalizedString
			/**
			 * {count} fields selected
			 */
			fieldsSelected: (arg: { count: unknown }) => LocalizedString
			/**
			 * Config Field
			 */
			configField: () => LocalizedString
			/**
			 * Next step
			 */
			nextStep: () => LocalizedString
		}
	}
	common: {
		/**
		 * Back
		 */
		back: () => LocalizedString
		/**
		 * Error
		 */
		error: () => LocalizedString
		/**
		 * Duplicate
		 */
		duplicate: () => LocalizedString
		/**
		 * Description
		 */
		description: () => LocalizedString
		/**
		 * Cancel
		 */
		cancel: () => LocalizedString
		/**
		 * Create
		 */
		create: () => LocalizedString
		/**
		 * Select
		 */
		select: () => LocalizedString
		/**
		 * Event
		 */
		event: () => LocalizedString
		/**
		 * Creating
		 */
		creating: () => LocalizedString
		/**
		 * Search
		 */
		search: () => LocalizedString
		/**
		 * Confirm
		 */
		confirm: () => LocalizedString
		/**
		 * Update
		 */
		update: () => LocalizedString
		/**
		 * Continue
		 */
		'continue': () => LocalizedString
		/**
		 * Submit
		 */
		submit: () => LocalizedString
		/**
		 * Delete
		 */
		'delete': () => LocalizedString
		/**
		 * Settings
		 */
		settings: () => LocalizedString
		/**
		 * Save
		 */
		save: () => LocalizedString
		/**
		 * Language
		 */
		language: () => LocalizedString
		/**
		 * Data
		 */
		data: () => LocalizedString
		/**
		 * Auth
		 */
		auth: () => LocalizedString
		/**
		 * Developer
		 */
		developer: () => LocalizedString
		/**
		 * Name
		 */
		name: () => LocalizedString
		/**
		 * Danger Zone
		 */
		dangerZone: () => LocalizedString
		/**
		 * Remove
		 */
		remove: () => LocalizedString
		/**
		 * Account and Space Settings
		 */
		accountAndSpaceSettings: () => LocalizedString
		/**
		 * Email
		 */
		email: () => LocalizedString
		/**
		 * Role
		 */
		role: () => LocalizedString
		/**
		 * Action
		 */
		action: () => LocalizedString
		/**
		 * Status
		 */
		status: () => LocalizedString
		/**
		 * Required
		 */
		required: () => LocalizedString
		/**
		 * Enabled
		 */
		enabled: () => LocalizedString
		/**
		 * Enable Condition
		 */
		enableCondition: () => LocalizedString
		/**
		 * Type
		 */
		type: () => LocalizedString
		/**
		 * Load more
		 */
		loadMore: () => LocalizedString
		/**
		 * Today
		 */
		today: () => LocalizedString
		/**
		 * Clear
		 */
		clear: () => LocalizedString
		/**
		 * Updated
		 */
		updated: () => LocalizedString
		/**
		 * Now
		 */
		now: () => LocalizedString
		/**
		 * Import
		 */
		'import': () => LocalizedString
	}
	share: {
		/**
		 * Share
		 */
		title: () => LocalizedString
		/**
		 * Share URL
		 */
		shareUrl: () => LocalizedString
		/**
		 * IFrame URL
		 */
		iframeUrl: () => LocalizedString
		/**
		 * Share ID
		 */
		shareId: () => LocalizedString
		/**
		 * Enable sharing
		 */
		enable: () => LocalizedString
		/**
		 * Copied to clipboard
		 */
		copied: () => LocalizedString
		/**
		 * Share
		 */
		button: () => LocalizedString
	}
	widget: {
		/**
		 * Widget
		 */
		title: () => LocalizedString
		/**
		 * Widgets
		 */
		button: () => LocalizedString
		/**
		 * Name
		 */
		name: () => LocalizedString
		/**
		 * Add Widget
		 */
		add: () => LocalizedString
		/**
		 * Type
		 */
		type: () => LocalizedString
		/**
		 * Edit Name
		 */
		editName: () => LocalizedString
		/**
		 * Duplicate Widget {name}
		 */
		duplicate: (arg: { name: unknown }) => LocalizedString
		/**
		 * Delete Widget {name}
		 */
		'delete': (arg: { name: unknown }) => LocalizedString
		deleteConfirm: {
			/**
			 * Delete Widget {name}?
			 */
			title: (arg: { name: unknown }) => LocalizedString
			/**
			 * This action cannot be undone. This will permanently delete this widget. and remove your data from our servers.
			 */
			description: () => LocalizedString
		}
		/**
		 * Count
		 */
		count: () => LocalizedString
		/**
		 * Aggregate
		 */
		aggregate: () => LocalizedString
		/**
		 * Filters
		 */
		filters: () => LocalizedString
	}
	dashboard: {
		/**
		 * Dashboards
		 */
		dashboards: () => LocalizedString
		/**
		 * Create Dashboard
		 */
		create: () => LocalizedString
		/**
		 * Dashboard's public display name.
		 */
		nameDescription: () => LocalizedString
		/**
		 * Update Dashboard Name
		 */
		updateName: () => LocalizedString
		/**
		 * Duplicate Dashboard
		 */
		duplicateDashboard: () => LocalizedString
		/**
		 * Delete Dashboard
		 */
		deleteDashboard: () => LocalizedString
		/**
		 * Confirm to delete dashboard?
		 */
		confirmDeleteDashboard: () => LocalizedString
		/**
		 * This action cannot be undone. This will permanently delete your dashboard and remove your data from our servers.
		 */
		confirmDeleteDashboardDescription: () => LocalizedString
		/**
		 * Confirm to duplicate dashboard?
		 */
		duplicateDashboardDescription: () => LocalizedString
		/**
		 * Duplicate Dashboard
		 */
		duplicateDashboardConfirm: () => LocalizedString
		/**
		 * Update Dashboard
		 */
		updateDashboard: () => LocalizedString
	}
}

export type Formatters = {
	number: (value: unknown) => unknown
}
