// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	table: {
		ops: {
			/**
			 * =
			 */
			eq: string
			/**
			 * !​=
			 */
			neq: string
			/**
			 * c​o​n​t​a​i​n​s
			 */
			contains: string
			/**
			 * n​o​t​ ​c​o​n​t​a​i​n​s
			 */
			does_not_contain: string
			/**
			 * s​t​a​r​t​s​ ​w​i​t​h
			 */
			starts_with: string
			/**
			 * e​n​d​s​ ​w​i​t​h
			 */
			ends_with: string
			/**
			 * i​s​ ​e​m​p​t​y
			 */
			is_empty: string
			/**
			 * i​s​ ​n​o​t​ ​e​m​p​t​y
			 */
			is_not_empty: string
			/**
			 * m​i​n
			 */
			min: string
			/**
			 * m​a​x
			 */
			max: string
			/**
			 * >
			 */
			gt: string
			/**
			 * >​=
			 */
			gte: string
			/**
			 * <
			 */
			lt: string
			/**
			 * <​=
			 */
			lte: string
			/**
			 * i​n
			 */
			'in': string
			/**
			 * n​o​t​ ​i​n
			 */
			nin: string
			/**
			 * a​n​y​ ​o​f
			 */
			any_of: string
			/**
			 * n​o​t​ ​a​n​y​ ​o​f
			 */
			not_any_of: string
			/**
			 * i​s​ ​s​a​m​e​ ​d​a​y
			 */
			is_same_day: string
			/**
			 * i​s​ ​n​o​t​ ​s​a​m​e​ ​d​a​y
			 */
			is_not_same_day: string
			/**
			 * i​s​ ​t​o​d​a​y
			 */
			is_tody: string
			/**
			 * i​s​ ​n​o​t​ ​t​o​d​a​y
			 */
			is_not_today: string
			/**
			 * i​s​ ​a​f​t​e​r​ ​t​o​d​a​y
			 */
			is_after_today: string
			/**
			 * i​s​ ​b​e​f​o​r​e​ ​t​o​d​a​y
			 */
			is_before_today: string
			/**
			 * i​s​ ​t​o​m​o​r​r​o​w
			 */
			is_tomorrow: string
			/**
			 * i​s​ ​n​o​t​ ​t​o​m​o​r​r​o​w
			 */
			is_not_tomorrow: string
			/**
			 * i​s​ ​a​f​t​e​r​ ​t​o​m​o​r​r​o​w
			 */
			is_after_tomorrow: string
			/**
			 * i​s​ ​b​e​f​o​r​e​ ​t​o​m​o​r​r​o​w
			 */
			is_before_tommorow: string
			/**
			 * i​s​ ​y​e​s​t​e​r​d​a​y
			 */
			is_yesterday: string
			/**
			 * i​s​ ​n​o​t​ ​y​e​s​t​e​r​d​a​y
			 */
			is_not_yesterday: string
			/**
			 * i​s​ ​a​f​t​e​r​ ​y​e​s​t​e​r​d​a​y
			 */
			is_after_yesterday: string
			/**
			 * i​s​ ​b​e​f​o​r​e​ ​y​e​s​t​e​r​d​a​y
			 */
			is_before_yesterday: string
			/**
			 * i​s​ ​b​e​f​o​r​e
			 */
			is_before: string
			/**
			 * i​s​ ​n​o​t​ ​b​e​f​o​r​e
			 */
			is_not_before: string
			/**
			 * i​s​ ​a​f​t​e​r
			 */
			is_after: string
			/**
			 * i​s​ ​n​o​t​ ​a​f​t​e​r
			 */
			is_not_after: string
			/**
			 * i​s​ ​t​r​u​e
			 */
			is_true: string
			/**
			 * i​s​ ​f​a​l​s​e
			 */
			is_false: string
		}
		fieldTypes: {
			/**
			 * S​t​r​i​n​g
			 */
			string: string
			/**
			 * L​o​n​g​ ​T​e​x​t
			 */
			longText: string
			/**
			 * N​u​m​b​e​r
			 */
			number: string
			/**
			 * D​a​t​e
			 */
			date: string
			/**
			 * D​a​t​e​ ​R​a​n​g​e
			 */
			dateRange: string
			/**
			 * I​D
			 */
			id: string
			/**
			 * C​r​e​a​t​e​d​ ​A​t
			 */
			createdAt: string
			/**
			 * A​u​t​o​ ​I​n​c​r​e​m​e​n​t
			 */
			autoIncrement: string
			/**
			 * U​p​d​a​t​e​d​ ​A​t
			 */
			updatedAt: string
			/**
			 * C​r​e​a​t​e​d​ ​B​y
			 */
			createdBy: string
			/**
			 * U​p​d​a​t​e​d​ ​B​y
			 */
			updatedBy: string
			/**
			 * R​e​f​e​r​e​n​c​e
			 */
			reference: string
			/**
			 * R​o​l​l​u​p
			 */
			rollup: string
			/**
			 * S​e​l​e​c​t
			 */
			select: string
			/**
			 * R​a​t​i​n​g
			 */
			rating: string
			/**
			 * E​m​a​i​l
			 */
			email: string
			/**
			 * U​R​L
			 */
			url: string
			/**
			 * A​t​t​a​c​h​m​e​n​t
			 */
			attachment: string
			/**
			 * J​S​O​N
			 */
			json: string
			/**
			 * C​h​e​c​k​b​o​x
			 */
			checkbox: string
			/**
			 * U​s​e​r
			 */
			user: string
			/**
			 * C​u​r​r​e​n​c​y
			 */
			currency: string
			/**
			 * D​u​r​a​t​i​o​n
			 */
			duration: string
			/**
			 * B​u​t​t​o​n
			 */
			button: string
			/**
			 * P​e​r​c​e​n​t​a​g​e
			 */
			percentage: string
			/**
			 * F​o​r​m​u​l​a
			 */
			formula: string
		}
		rollupFns: {
			/**
			 * M​i​n
			 */
			min: string
			/**
			 * M​a​x
			 */
			max: string
			/**
			 * S​u​m
			 */
			sum: string
			/**
			 * A​v​e​r​a​g​e
			 */
			average: string
			/**
			 * C​o​u​n​t
			 */
			count: string
			/**
			 * L​o​o​k​u​p
			 */
			lookup: string
		}
		aggregateFns: {
			/**
			 * M​i​n
			 */
			min: string
			/**
			 * M​a​x
			 */
			max: string
			/**
			 * S​u​m
			 */
			sum: string
			/**
			 * C​o​u​n​t
			 */
			count: string
			/**
			 * E​m​p​t​y
			 */
			count_empty: string
			/**
			 * U​n​i​q​u​e
			 */
			count_uniq: string
			/**
			 * F​i​l​l​e​d
			 */
			count_not_empty: string
			/**
			 * P​e​r​c​e​n​t​ ​E​m​p​t​y
			 */
			percent_empty: string
			/**
			 * P​e​r​c​e​n​t​ ​F​i​l​l​e​d
			 */
			percent_not_empty: string
			/**
			 * P​e​r​c​e​n​t​ ​U​n​i​q​u​e
			 */
			percent_uniq: string
			/**
			 * A​v​e​r​a​g​e
			 */
			avg: string
			/**
			 * T​r​u​e
			 */
			count_true: string
			/**
			 * F​a​l​s​e
			 */
			count_false: string
			/**
			 * P​e​r​c​e​n​t​ ​T​r​u​e
			 */
			percent_true: string
			/**
			 * P​e​r​c​e​n​t​ ​F​a​l​s​e
			 */
			percent_false: string
			/**
			 * S​t​a​r​t​ ​D​a​t​e​ ​M​a​x
			 */
			start_max: string
			/**
			 * E​n​d​ ​D​a​t​e​ ​M​a​x
			 */
			end_max: string
			/**
			 * S​t​a​r​t​ ​D​a​t​e​ ​M​i​n
			 */
			start_min: string
			/**
			 * E​n​d​ ​D​a​t​e​ ​M​i​n
			 */
			end_min: string
		}
		workspaceRoles: {
			/**
			 * O​w​n​e​r
			 */
			owner: string
			/**
			 * A​d​m​i​n
			 */
			admin: string
			/**
			 * E​d​i​t​o​r
			 */
			editor: string
			/**
			 * V​i​e​w​e​r
			 */
			viewer: string
		}
		macros: {
			/**
			 * C​u​r​r​e​n​t​ ​U​s​e​r
			 */
			'@me': string
			/**
			 * N​o​w
			 */
			'@now': string
			/**
			 * T​o​d​a​y
			 */
			'@today': string
			/**
			 * Y​e​s​t​e​r​d​a​y
			 */
			'@yesterday': string
			/**
			 * T​o​m​o​r​r​o​w
			 */
			'@tomorrow': string
		}
		viewTypes: {
			/**
			 * G​r​i​d
			 */
			grid: string
			/**
			 * K​a​n​b​a​n
			 */
			kanban: string
			/**
			 * G​a​l​l​e​r​y
			 */
			gallery: string
			/**
			 * L​i​s​t
			 */
			list: string
			/**
			 * C​a​l​e​n​d​a​r
			 */
			calendar: string
		}
		widgetTypes: {
			/**
			 * A​g​g​r​e​g​a​t​e
			 */
			aggregate: string
			/**
			 * C​h​a​r​t
			 */
			chart: string
			/**
			 * T​a​b​l​e
			 */
			table: string
		}
	}
}

export type TranslationFunctions = {
	table: {
		ops: {
			/**
			 * =
			 */
			eq: () => LocalizedString
			/**
			 * !=
			 */
			neq: () => LocalizedString
			/**
			 * contains
			 */
			contains: () => LocalizedString
			/**
			 * not contains
			 */
			does_not_contain: () => LocalizedString
			/**
			 * starts with
			 */
			starts_with: () => LocalizedString
			/**
			 * ends with
			 */
			ends_with: () => LocalizedString
			/**
			 * is empty
			 */
			is_empty: () => LocalizedString
			/**
			 * is not empty
			 */
			is_not_empty: () => LocalizedString
			/**
			 * min
			 */
			min: () => LocalizedString
			/**
			 * max
			 */
			max: () => LocalizedString
			/**
			 * >
			 */
			gt: () => LocalizedString
			/**
			 * >=
			 */
			gte: () => LocalizedString
			/**
			 * <
			 */
			lt: () => LocalizedString
			/**
			 * <=
			 */
			lte: () => LocalizedString
			/**
			 * in
			 */
			'in': () => LocalizedString
			/**
			 * not in
			 */
			nin: () => LocalizedString
			/**
			 * any of
			 */
			any_of: () => LocalizedString
			/**
			 * not any of
			 */
			not_any_of: () => LocalizedString
			/**
			 * is same day
			 */
			is_same_day: () => LocalizedString
			/**
			 * is not same day
			 */
			is_not_same_day: () => LocalizedString
			/**
			 * is today
			 */
			is_tody: () => LocalizedString
			/**
			 * is not today
			 */
			is_not_today: () => LocalizedString
			/**
			 * is after today
			 */
			is_after_today: () => LocalizedString
			/**
			 * is before today
			 */
			is_before_today: () => LocalizedString
			/**
			 * is tomorrow
			 */
			is_tomorrow: () => LocalizedString
			/**
			 * is not tomorrow
			 */
			is_not_tomorrow: () => LocalizedString
			/**
			 * is after tomorrow
			 */
			is_after_tomorrow: () => LocalizedString
			/**
			 * is before tomorrow
			 */
			is_before_tommorow: () => LocalizedString
			/**
			 * is yesterday
			 */
			is_yesterday: () => LocalizedString
			/**
			 * is not yesterday
			 */
			is_not_yesterday: () => LocalizedString
			/**
			 * is after yesterday
			 */
			is_after_yesterday: () => LocalizedString
			/**
			 * is before yesterday
			 */
			is_before_yesterday: () => LocalizedString
			/**
			 * is before
			 */
			is_before: () => LocalizedString
			/**
			 * is not before
			 */
			is_not_before: () => LocalizedString
			/**
			 * is after
			 */
			is_after: () => LocalizedString
			/**
			 * is not after
			 */
			is_not_after: () => LocalizedString
			/**
			 * is true
			 */
			is_true: () => LocalizedString
			/**
			 * is false
			 */
			is_false: () => LocalizedString
		}
		fieldTypes: {
			/**
			 * String
			 */
			string: () => LocalizedString
			/**
			 * Long Text
			 */
			longText: () => LocalizedString
			/**
			 * Number
			 */
			number: () => LocalizedString
			/**
			 * Date
			 */
			date: () => LocalizedString
			/**
			 * Date Range
			 */
			dateRange: () => LocalizedString
			/**
			 * ID
			 */
			id: () => LocalizedString
			/**
			 * Created At
			 */
			createdAt: () => LocalizedString
			/**
			 * Auto Increment
			 */
			autoIncrement: () => LocalizedString
			/**
			 * Updated At
			 */
			updatedAt: () => LocalizedString
			/**
			 * Created By
			 */
			createdBy: () => LocalizedString
			/**
			 * Updated By
			 */
			updatedBy: () => LocalizedString
			/**
			 * Reference
			 */
			reference: () => LocalizedString
			/**
			 * Rollup
			 */
			rollup: () => LocalizedString
			/**
			 * Select
			 */
			select: () => LocalizedString
			/**
			 * Rating
			 */
			rating: () => LocalizedString
			/**
			 * Email
			 */
			email: () => LocalizedString
			/**
			 * URL
			 */
			url: () => LocalizedString
			/**
			 * Attachment
			 */
			attachment: () => LocalizedString
			/**
			 * JSON
			 */
			json: () => LocalizedString
			/**
			 * Checkbox
			 */
			checkbox: () => LocalizedString
			/**
			 * User
			 */
			user: () => LocalizedString
			/**
			 * Currency
			 */
			currency: () => LocalizedString
			/**
			 * Duration
			 */
			duration: () => LocalizedString
			/**
			 * Button
			 */
			button: () => LocalizedString
			/**
			 * Percentage
			 */
			percentage: () => LocalizedString
			/**
			 * Formula
			 */
			formula: () => LocalizedString
		}
		rollupFns: {
			/**
			 * Min
			 */
			min: () => LocalizedString
			/**
			 * Max
			 */
			max: () => LocalizedString
			/**
			 * Sum
			 */
			sum: () => LocalizedString
			/**
			 * Average
			 */
			average: () => LocalizedString
			/**
			 * Count
			 */
			count: () => LocalizedString
			/**
			 * Lookup
			 */
			lookup: () => LocalizedString
		}
		aggregateFns: {
			/**
			 * Min
			 */
			min: () => LocalizedString
			/**
			 * Max
			 */
			max: () => LocalizedString
			/**
			 * Sum
			 */
			sum: () => LocalizedString
			/**
			 * Count
			 */
			count: () => LocalizedString
			/**
			 * Empty
			 */
			count_empty: () => LocalizedString
			/**
			 * Unique
			 */
			count_uniq: () => LocalizedString
			/**
			 * Filled
			 */
			count_not_empty: () => LocalizedString
			/**
			 * Percent Empty
			 */
			percent_empty: () => LocalizedString
			/**
			 * Percent Filled
			 */
			percent_not_empty: () => LocalizedString
			/**
			 * Percent Unique
			 */
			percent_uniq: () => LocalizedString
			/**
			 * Average
			 */
			avg: () => LocalizedString
			/**
			 * True
			 */
			count_true: () => LocalizedString
			/**
			 * False
			 */
			count_false: () => LocalizedString
			/**
			 * Percent True
			 */
			percent_true: () => LocalizedString
			/**
			 * Percent False
			 */
			percent_false: () => LocalizedString
			/**
			 * Start Date Max
			 */
			start_max: () => LocalizedString
			/**
			 * End Date Max
			 */
			end_max: () => LocalizedString
			/**
			 * Start Date Min
			 */
			start_min: () => LocalizedString
			/**
			 * End Date Min
			 */
			end_min: () => LocalizedString
		}
		workspaceRoles: {
			/**
			 * Owner
			 */
			owner: () => LocalizedString
			/**
			 * Admin
			 */
			admin: () => LocalizedString
			/**
			 * Editor
			 */
			editor: () => LocalizedString
			/**
			 * Viewer
			 */
			viewer: () => LocalizedString
		}
		macros: {
			/**
			 * Current User
			 */
			'@me': () => LocalizedString
			/**
			 * Now
			 */
			'@now': () => LocalizedString
			/**
			 * Today
			 */
			'@today': () => LocalizedString
			/**
			 * Yesterday
			 */
			'@yesterday': () => LocalizedString
			/**
			 * Tomorrow
			 */
			'@tomorrow': () => LocalizedString
		}
		viewTypes: {
			/**
			 * Grid
			 */
			grid: () => LocalizedString
			/**
			 * Kanban
			 */
			kanban: () => LocalizedString
			/**
			 * Gallery
			 */
			gallery: () => LocalizedString
			/**
			 * List
			 */
			list: () => LocalizedString
			/**
			 * Calendar
			 */
			calendar: () => LocalizedString
		}
		widgetTypes: {
			/**
			 * Aggregate
			 */
			aggregate: () => LocalizedString
			/**
			 * Chart
			 */
			chart: () => LocalizedString
			/**
			 * Table
			 */
			table: () => LocalizedString
		}
	}
}

export type Formatters = {}
