query GetShareBaseData($shareId: ID!) {
  member {
    role
    user {
      email
      id
      username
    }
  }

  baseByShare(shareId: $shareId) {
    id
    name

    tables {
      id
      name

      forms {
        id
        name
        fields
        description
        option {
          backgroundColor
        }
      }

      views {
        id
        name
        isDefault
      }
    }
  }
}
