query GetShareBaseData($shareId: ID!) {
  member {
    role
    user {
      email
      id
      username
    }
  }

  baseByShare(shareId: $shareId) {
    id
    name
    option {
      allowTemplate
    }

    tables {
      id
      name

      views {
        id
        name
        isDefault
      }
    }
  }
}
