query GetIndexQuery {
  space {
    id
    name
    isPersonal
  }

  tables {
    id
    name
    baseId

    views {
      id
      name
      type
      isDefault
    }

    recordsCount
  }

  bases {
    id
    name
  }

  member {
    role
  }
}
