query GetDashboardQuery($dashboardId: ID!) {
  dashboard(id: $dashboardId) {
    id
    name
    baseId
    spaceId
    widgets {
      table {
        id
      }
      widget {
        id
        name
        item
      }
    }
  }
}
