export * from './get-foreign-records.query.handler.js'
export * from './get-foreign-records.query.input.js'
export * from './get-foreign-records.query.interface.js'
export * from './get-foreign-records.query.js'
export * from './get-foreign-records.query.output.js'
