query GetBaseQuery($baseId: ID!) {
  base(id: $baseId) {
    id
    name
    option {
      allowTemplate
    }

    share {
      enabled
      id
    }

    tables {
      id
      name
    }
  }
}
