import type { IColor, IFieldType } from '@undb/core'

export const icons: Record<IFieldType, string> = {
	string: 'circle-letter-a',
	number: '123',
	id: 'key',
	'auto-increment': 'sort-ascending-2',
	average: 'math-x-divide-2',
	bool: 'square-check',
	collaborator: 'user',
	'date-range': 'calendar-time',
	select: 'list',
	'multi-select': 'list-check',
	date: 'calendar',
	'created-at': 'calendar-plus',
	'updated-at': 'calendar-stats',
	email: 'mail',
	qrcode: 'qrcode',
	url: 'link',
	json: 'json',
	color: 'palette',
	reference: 'relation-many-to-many',
	tree: 'hierarchy',
	parent: 'binary-tree',
	rating: 'stars',
	currency: 'currency-yuan',
	count: 'calculator',
	lookup: 'search',
	sum: 'sum',
	attachment: 'paperclip',
	min: 'arrow-down',
	max: 'arrow-up',
	'created-by': 'calendar-plus',
	'updated-by': 'calendar-stats',
}

export const getIconClass = (type: IFieldType) => `ti ti-${icons[type]}`

export const colors: Record<IColor, string> = {
	slate: 'bg-slate-500',
	gray: 'bg-gray-500',
	zinc: 'bg-zinc-500',
	neutral: 'bg-neutral-500',
	stone: 'bg-stone-500',
	red: 'bg-red-500',
	orange: 'bg-orange-500',
	amber: 'bg-amber-500',
	yellow: 'bg-yellow-500',
	lime: 'bg-lime-500',
	green: 'bg-green-500',
	emerald: 'bg-emerald-500',
	teal: 'bg-teal-500',
	cyan: 'bg-cyan-500',
	sky: 'bg-sky-500',
	blue: 'bg-blue-500',
	indigo: 'bg-indigo-500',
	violet: 'bg-violet-500',
	purple: 'bg-purple-500',
	fuchsia: 'bg-fuchsia-500',
	pink: 'bg-pink-500',
	rose: 'bg-rose-500',
}
